### ISSUE TITLE
pydal - cx_Oracle installed Auto Ticket on opening index

### ISSUE THREAD

**Issue by preactive** [web2py/web2py#1082]
When point DAL to oracle://un/pw@server:port/sid it pumps out a ticket when trying to navigate to any page.

 I installed the following:

sudo rpm -Uvh .....

oracle-instantclient11.2-basic-11.2.0.4.0-1.x86_64.rpm
oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm
oracle-instantclient11.2-jdbc-11.2.0.4.0-1.x86_64.rpm
oracle-instantclient11.2-odbc-11.2.0.4.0-1.x86_64.rpm
oracle-instantclient11.2-sqlplus-11.2.0.4.0-1.x86_64.rpm
oracle-instantclient11.2-tools-11.2.0.4.0-1.x86_64.rpm

then 

cx_Oracle-5.1.2-11g-py27-1.x86_64.rpm
_________________________________________
Opening up web2py from CLI i get the following:
'''
$ python web2py.py
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2015
Version 2.12.3-stable+timestamp.2015.08.19.00.18.03
Database drivers available: cx_Oracle, pymysql, imaplib, sqlite3, pg8000, pyodbc
'''
-So it web2py is seeing the Oracle driver.
_________________________________________
Opening up the page after I point the DAL to oracle://..... i get the following when trying to goto index:
'''
Traceback (most recent call last):
  File "/opt/www-data/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/opt/www-data/web2py/applications/test/models/db.py", line 20, in <module>
    
db = DAL(myconf.take('db.uri'), pool_size=myconf.take('db.pool_size', cast=int), check_reserved=['all'])
  File "/opt/www-data/web2py/gluon/packages/dal/pydal/base.py", line 174, in __call__
    obj = super(MetaDAL, cls).__call__(*args, **kwargs)
  File "/opt/www-data/web2py/gluon/packages/dal/pydal/base.py", line 459, in __init__
    raise RuntimeError("Failure to connect, tried %d times:\n%s" % (attempts, tb))
RuntimeError: Failure to connect, tried 5 times:
Traceback (most recent call last):
  File "/opt/www-data/web2py/gluon/packages/dal/pydal/base.py", line 437, in __init__
    self._adapter = ADAPTERS[self._dbname](**kwargs)
  File "/opt/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 57, in __call__
    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)
  File "/opt/www-data/web2py/gluon/packages/dal/pydal/adapters/oracle.py", line 105, in __init__
    if do_connect: self.find_driver(adapter_args,uri)
  File "/opt/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 188, in find_driver
    raise RuntimeError("no driver available %s" % str(self.drivers))
RuntimeError: no driver available ('cx_Oracle',)
'''
-So here from the user side I get this ticket generated
_________________________________________

Additional system info:

2.12.3-stable+timestamp.2015.08.19.00.18.03
(Running on Apache/2.4.16 (Fedora 22 Workstation) OpenSSL/1.0.1k-fips mod_wsgi/4.4.8 Python/2.7.10, Python 2.7.10)

Google Groups Topic:
https://groups.google.com/forum/#!topic/web2py/4Y1Yx86wzl4

**Comment by preactive** [comment]
Resolved,  was user permissions for service accounts to drivers and the installation method of said drivers.  Will post Writeup on "https://groups.google.com/forum/#!topic/web2py/4Y1Yx86wzl4" when I do a clean OS install from script and working 100%.

Will close sister ticket "https://github.com/web2py/pydal/issues/299" on pyDAL git tracker.
