### ISSUE TITLE
databases folder missing running in a shell a fresh web2py

### ISSUE THREAD

**Issue by ilvalle** [web2py/web2py#1104]
On a fresh web2py environment, running ```python web2py.py -S welcome -R test.py``` fails raising the following:
```
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2015
Version 2.12.3-stable+timestamp.2015.08.18.19.14.07
Database drivers available: psycopg2, pymysql, imaplib, sqlite3, pg8000, pyodbc
Traceback (most recent call last):
  File "/tmp/web2py/gluon/shell.py", line 263, in run
    execfile(startfile, _env)
  File "test.py", line 7, in <module>
    db.define_table('unicode_test', Field('test', 'string'))
  File "/tmp/web2py/gluon/packages/dal/pydal/base.py", line 834, in define_table
    table = self.lazy_define_table(tablename,*fields,**args)
  File "/tmp/web2py/gluon/packages/dal/pydal/base.py", line 873, in lazy_define_table
    polymodel=polymodel)
  File "/tmp/web2py/gluon/packages/dal/pydal/adapters/base.py", line 480, in create_table
    query), table)
  File "/tmp/web2py/gluon/packages/dal/pydal/adapters/base.py", line 212, in log
    logfile = self.file_open(table._loggername, 'ab')
  File "/tmp/web2py/gluon/packages/dal/pydal/adapters/base.py", line 155, in file_open
    fileobj = portalocker.LockedFile(filename,mode)
  File "/tmp/web2py/gluon/packages/dal/pydal/contrib/portalocker.py", line 118, in __init__
    self.file = open(filename, mode.replace('w', 'a'))
IOError: [Errno 2] No such file or directory: 'applications/welcome/databases/sql.log'
```
Creating the ```applications/welcome/databases``` folder fixed it

**Comment by cassiobotaro** [comment]
It's related with pydal and how log file works. I think @gi0baro can help here. 
BaseAdapter.set_folder don't exists anymore?
https://github.com/web2py/web2py/blob/master/gluon/compileapp.py#L440

**Comment by mdipierro** [comment]
If an app is missing required folders, it must be called at least on, for the folders to be created. This is a corner case.
