### ISSUE TITLE
Validating SQLFORM unique field raises exception

### ISSUE THREAD

**Issue by oldncrabby** [web2py/web2py#1162]
I have a db table, `t_trial`, with the following field:

    Field( 'f_UKI_ID', 'integer', label="UKI ID", unique=True, required=True ),

I create an `SQLFORM` for this table:

     def request_trial():
        form = SQLFORM(db.t_trial)
        if form.process(dbio=False).accepted:
            session.flash = "Trial Requested"
            redirect( URL(f="index", user_signature=True) )
        return locals()

If I leave the field empty when submitting, I get the following exception:

    Traceback (most recent call last):
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/restricted.py", line 227, in restricted
        exec ccode in environment
      File "/Users/scott_mbp/Dropbox/web2py_uki/applications/init_bkup/controllers/default.py", line 494, in <module>
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/globals.py", line 412, in <lambda>
        self._caller = lambda f: f()
      File "/Users/scott_mbp/Dropbox/web2py_uki/applications/init_bkup/controllers/default.py", line 480, in request_trial
        if form.process(dbio=False).accepted:
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/html.py", line 2304, in process
        self.validate(**kwargs)
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/html.py", line 2241, in validate
        if self.accepts(**kwargs):
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/sqlhtml.py", line 1505, in accepts
        **kwargs
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/html.py", line 2122, in accepts
        status = self._traverse(status, hideerror)
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/html.py", line 888, in _traverse
        newstatus = c._traverse(status, hideerror) and newstatus
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/html.py", line 888, in _traverse
        newstatus = c._traverse(status, hideerror) and newstatus
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/html.py", line 888, in _traverse
        newstatus = c._traverse(status, hideerror) and newstatus
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/html.py", line 888, in _traverse
        newstatus = c._traverse(status, hideerror) and newstatus
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/html.py", line 895, in _traverse
        newstatus = self._validate()
      File "/Users/scott_mbp/Dropbox/web2py_uki/gluon/html.py", line 1863, in _validate
        raise Exception(msg)
    Exception: Validation error, field:f_UKI_ID <gluon.validators.IS_NOT_IN_DB object at 0x10e6bfa10>

If I add a `requires` parameter to the field, to have the form catch when the field is empty, I get the expected error message.  But it doesn't seem like this should raise an exception.

**Comment by MOROZOV196** [comment]
morozzz
