### ISSUE TITLE
Command line option "-M" not create databases dir

### ISSUE THREAD

**Issue by navicor90** [web2py/web2py#1186]
In a clean deploy: 
* Do not load http://127.0.0.1/ (or the corresponding url) on your browser
* Run your script for database population  ( eg python2.7 web2py.py -v -S pnp/ -M -R my_script.py ) 
 The system **does not create databases/ directory, and fails**.  I run with with -M option since I want create the model.

The  exception is:
```
Traceback (most recent call last):
  File "/home/pnp/pnp/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "applications/pnp/models/db.py", line 65, in <module>
    auth.define_tables(username=True, signature=False)
  File "/home/pnp/pnp/gluon/tools.py", line 2333, in define_tables
    format='%(username)s'))
  File "/home/pnp/pnp/gluon/packages/dal/pydal/base.py", line 834, in define_table
    table = self.lazy_define_table(tablename,*fields,**args)
  File "/home/pnp/pnp/gluon/packages/dal/pydal/base.py", line 873, in lazy_define_table
    polymodel=polymodel)
  File "/home/pnp/pnp/gluon/packages/dal/pydal/adapters/base.py", line 480, in create_table
    query), table)
  File "/home/pnp/pnp/gluon/packages/dal/pydal/adapters/base.py", line 212, in log
    logfile = self.file_open(table._loggername, 'ab')
  File "/home/pnp/pnp/gluon/packages/dal/pydal/adapters/base.py", line 155, in file_open
    fileobj = portalocker.LockedFile(filename,mode)
  File "/home/pnp/pnp/gluon/packages/dal/pydal/contrib/portalocker.py", line 118, in __init__
    self.file = open(filename, mode.replace('w', 'a'))
IOError: [Errno 2] No such file or directory: 'applications/pnp/databases/sql.log'
```

If I create the databases/ directory first than the script ,**the execution runs normally.**

**Comment by niphlod** [comment]
uhm......why can't you assume a "clean deploy" contains the databases/ directory ?

**Comment by mdipierro** [comment]
This should create the folder.

**Comment by mdipierro** [comment]
I cannot reproduce this problem.
