### ISSUE TITLE
Error due to outdated API call in mercurial module

### ISSUE THREAD

**Issue by SpotlightKid** [web2py/web2py#1245]
I created a new app, changed default controller, then selected "Versioning" from the admin menu in the header, entered "Initial commit" into the comment field and clicked the "Commit button".

I got an "Internal error" and the ticket shows this traceback:

```
Traceback (most recent call last):
  File "/home/chris/src/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/chris/src/web2py/applications/admin/controllers/mercurial.py", line 87, in <module>
  File "/home/chris/src/web2py/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/home/chris/src/web2py/applications/admin/controllers/mercurial.py", line 50, in commit
    addremove(repo)
TypeError: addremove() takes at least 3 arguments (1 given)
``` 

Examining `mercurial.scmutil.addremove()` shows the following signature.

    addremove(repo, matcher, prefix, opts=None, dry_run=None, similarity=None)

So it seems the signature has changed and web2py is using an outdated API.

web2py is latest from Git (Version 2.14.1-beta+timestamp.2016.03.19.17.15.25) and mercurial is 3.7.2 on Arch Linux.

**Comment by leonelcamara** [comment]
People working on a fix should also see:
https://groups.google.com/forum/#!topic/web2py/BfC58Ssj9ps
