### ISSUE TITLE
scheduler break when disconnect db

### ISSUE THREAD

**Issue by wanghaiqing2015** [web2py/web2py#1350]
scheduler will break when restart db service. i think that scheduler will auto connect to db again.

this is error log:

2016-06-06 21:48:28,260 - web2py.scheduler.whq#6492 - ERROR - Error retrieving s
tatus
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "C:\Users\root\Desktop\web2py_win\web2py\gluon\scheduler.py", line 440, i
n run
    self.send_heartbeat(counter)
  File "C:\Users\root\Desktop\web2py_win\web2py\gluon\scheduler.py", line 1039,
in send_heartbeat
    db.rollback()
  File "C:\Users\root\Desktop\web2py_win\web2py\pydal\base.py", line 956, in rol
lback
    self._adapter.rollback()
  File "C:\Users\root\Desktop\web2py_win\web2py\pydal\adapters\base.py", line 13
39, in rollback
    return self.connection.rollback()
  File "C:\Users\root\Desktop\web2py_win\web2py\gluon\contrib\pymysql\connection
s.py", line 640, in rollback
    self.errorhandler(None, exc, value)
  File "C:\Users\root\Desktop\web2py_win\web2py\gluon\contrib\pymysql\connection
s.py", line 200, in defaulterrorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.error'>, error(10053, ''))

**Comment by niphlod** [comment]
a backend is REQUIRED to have the scheduler running. That's why the process needs to be managed as a service, that restarts it in case of failures.

**Comment by wanghaiqing2015** [comment]
scheduler how to be managed as a service ? 

Can you give me a little advice. Thanks.

**Comment by niphlod** [comment]
The web2py book has examples for Linux and Windows.
Il 07 giu 2016 3:29 AM, "wanghaiqing2015" <notifications@github.com> ha
scritto:

**Comment by wanghaiqing2015** [comment]
thanks.
