### ISSUE TITLE
Missing parentheses in call to 'exec' (qdb.py, line 338)

### ISSUE THREAD

**Issue by kelsa-pi** [web2py/web2py#1471]
Ticket ID

127.0.0.1.2016-09-24.19-01-42.d059899a-f956-4dbe-8a51-bd5515ae3222
<class 'SyntaxError'> Missing parentheses in call to 'exec' (qdb.py, line 338)
Verzija
web2py™ 	Version 2.14.6-stable+timestamp.2016.05.09.19.18.48
Python 	Python 3.5.2: /usr/bin/python3 (prefix: /usr)
Traceback

Traceback (most recent call last):
  File "/home/sasa/WorkDir/project/web2py/gluon/restricted.py", line 220, in restricted
    exec(ccode, environment)
  File "/home/sasa/WorkDir/project/web2py/applications/admin/controllers/debug.py", line 7, in <module>
    from gluon.debug import communicate, web_debugger, qdb_debugger
  File "/home/sasa/WorkDir/project/web2py/gluon/custom_import.py", line 111, in custom_importer
    return NATIVE_IMPORTER(name, globals, locals, fromlist, level)
  File "/home/sasa/WorkDir/project/web2py/gluon/debug.py", line 92, in <module>
    import gluon.contrib.qdb as qdb
  File "/home/sasa/WorkDir/project/web2py/gluon/custom_import.py", line 111, in custom_importer
    return NATIVE_IMPORTER(name, globals, locals, fromlist, level)
  File "/home/sasa/WorkDir/project/web2py/gluon/contrib/qdb.py", line 338
    exec code in globals, locals
            ^
SyntaxError: Missing parentheses in call to 'exec'

**Comment by ilvalle** [comment]
qdb has been renamed dbg(https://github.com/reingart/dbg) and the updated version already support py3
