### ISSUE TITLE
lazyT in _compat (PY2, to_bytes())

### ISSUE THREAD

**Issue by zvolsky** [web2py/web2py#1534]
Probably lazyT can entry into to_bytes(), but this is not prepared for lazyT instance.

Traceback (most recent call last):
  File "/home/mirek/mz/web2py/gluon/restricted.py", line 216, in restricted
    exec(ccode, environment)
  File "<string>", line 113, in <module>
  File "/home/mirek/mz/web2py/gluon/html.py", line 2802, in __init__
    self.text = to_bytes(text)
  File "/home/mirek/mz/web2py/gluon/_compat.py", line 67, in to_bytes
    raise TypeError('Expected bytes')
TypeError: Expected bytes
In 'text' is my message, lazyT instance.

**Comment by ilvalle** [comment]
@zvolsky would you mind to post a simple example to demonstrate the issue?

**Comment by zvolsky** [comment]
I'm sorry I read this to late and don't remember the scenario now.
But it was something very basic like T() inside controller, model, view or module.

**Comment by mdipierro** [comment]
closing until we can reproduce
