### ISSUE TITLE
Too many conflicts when generating session IDs

### ISSUE THREAD

**Issue by vdemario** [web2py/web2py#1543]
I've got this error happening on my app (complete filesystem redacted, but it shouldn't be relevant):

```
Traceback (most recent call last): (.../gluon/restricted.py:174)
  File ".../gluon/main.py", line 464, in wsgibase
    session._try_store_in_db(request, response)
  File ".../gluon/globals.py", line 1183, in _try_store_in_db
    record_id = table.insert(**dd)
  File ".../gluon/contrib/memdb.py", line 264, in insert
    raise RuntimeError("Too many ID conflicts")
RuntimeError: Too many ID conflicts
```

It's running on Google App Engine, with web2py Version 2.14.6-stable+timestamp.2016.05.10.00.21.47.

There were about 14k items on memcache with less than an 8% hit ratio. I'm not very familiar with this part of web2py/appengine but I'm assuming the session ids were being stored there.

Aren't the IDs UUIDs that are generated up to 3 times to avoid conflicts? A 3-way conflict with UUIDs should have a probability of conflict that's almost 0, right? It would be weird enough if it happened once, but we've seen 5 requests within 20 seconds of each other failing with this error.

**Comment by ilvalle** [comment]
you should debug a little more this issue, for example running on GAE a simple test as
```
import random
d = {}
conflicts=0

for i in range(10000000):
  uuid = "%s" % random.getrandbits(64)
  if uuid not in d:
    d[uuid] = 1
  else:
    conflicts=conflicts+1
``` 
and see the number of conflicts (if any)
