### ISSUE TITLE
auth.has_membership('groupname') error in menu.py GAE

### ISSUE THREAD

**Issue by jparga** [web2py/web2py#1573]
This error started today in a year working application.

`Unable to store in FILE: /base/data/home/apps/e~xxxxxxxxx/0.39/applications/xxxxxxxx/models/menu.py

Traceback (most recent call last):
  File "/base/data/home/apps/e~xxxxxxxxxxxx/0.39/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/base/data/home/apps/e~c/0.399/applications/xxxxxxx/models/menu.py", line 3, in <module>
    elif auth.has_membership('operaciones'):
  File "/base/data/home/apps/e~xxxxxxxxxx/0.39/gluon/tools.py", line 4360, in has_membership
    group_id = self.id_group(group_id)  # interpret group_id as a role
  File "/base/data/home/apps/e~xxxxxxxx/0.39918/gluon/tools.py", line 4331, in id_group
    rows = self.db(self.table_group().role == role).select()
  File "/base/data/home/apps/e~xxxxxxxxxxx/0.399180762665654903/gluon/packages/dal/pydal/objects.py", line 2020, in select
    return adapter.select(self.query, fields, attributes)
  File "/base/data/home/apps/e~xxxxxxx/0.399180762665654903/gluon/packages/dal/pydal/adapters/google_adapters.py", line 504, in select
    for t in fields] for item in items]
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/query.py", line 1810, in next
    self._more_results) = self._fut.get_result()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 890, in helper
    batch, i, ent = yield inq.getq()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/query.py", line 969, in run_to_queue
    batch = yield rpc
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 513, in _on_rpc_completion
    result = rpc.get_result()
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/datastore/datastore_query.py", line 2906, in __query_result_hook
    self._batch_shared.conn.check_rpc_success(rpc)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1371, in check_rpc_success
    raise _ToDatastoreError(err)
InternalError: internal error.`

The error raises width any auth.has_membership in menu.py. 
Deployed in Google Appengine

**Comment by mdipierro** [comment]
@jparga did the error show up after you upgraded web2py or pydal? Or was due to a datastore change?

**Comment by jparga** [comment]
Yes, after I upgrade web2py  to 2.14.6

It happened in several applications with no datastore changes.

El 20/6/2017 21:35, "mdipierro" <notifications@github.com> escribió:

@jparga <https://github.com/jparga> did the error show up after you
upgraded web2py or pydal? Or was due to a datastore change?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/web2py/web2py/issues/1573#issuecomment-309864666>, or mute
the thread

**Comment by mdipierro** [comment]
OK. will work on this asap.

**Comment by mdipierro** [comment]
Cannot reproduce with latest trunk code. Please reopen with more details if persists.
