### ISSUE TITLE
NameError: global name 'signature_list' is not defined

### ISSUE THREAD

**Issue by abhishesh** [web2py/web2py#1628]
```python
Traceback (most recent call last):
  File "/Users/abhishesh/Dropbox/WORK/web2py/gluon/restricted.py", line 216, in restricted
    exec(ccode, environment)
  File "/Users/abhishesh/Dropbox/WORK/web2py/applications/artemis/models/db.py", line 231, in <module>
    auth.define_tables(username=False, signature=False, enable_tokens=True)
  File "/Users/abhishesh/Dropbox/WORK/web2py/gluon/tools.py", line 2238, in define_tables
    settings.table_token_name, []) + signature_list
NameError: global name 'signature_list' is not defined
```

**Comment by leonelcamara** [comment]
I don't think this error exists in trunk, can you try it.

**Comment by abhishesh** [comment]
This happens when we do `enable_tokens=True` in `auth.define_tables()`. I'll check if there is a unit test around it !

**Comment by abhishesh** [comment]
by the way ! trunk == master is it !

**Comment by abhishesh** [comment]
Change to following in `gluon/tests/test_tools.py`

```python
self.auth.define_tables(username=True, signature=False, enable_tokens=True)
```
and run on master branch 
```
./web2py --run_system_tests
```
we get the error

**Comment by leonelcamara** [comment]
@abhishesh you are right! Good catch of a bug due to the auth refactoring, I'll look into it.
