### ISSUE TITLE
'Mongo' object has no attribute 'server_version_major'

### ISSUE THREAD

**Issue by remcoboerma** [web2py/web2py#1633]
Once every few requests i will get bugged down with this. 

> 'Mongo' object has no attribute 'server_version_major'
> Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 216, in restricted
    exec(ccode, environment)
  File "/home/www-data/web2py/applications/verzimpel_mozi_dev/models/db.py", line 67, in <module>
    is_admin = auth.has_membership('admin')
  File "/home/www-data/web2py/gluon/authapi.py", line 566, in has_membership
    group_id = self.id_group(group_id)  # interpret group_id as a role
  File "/home/www-data/web2py/gluon/authapi.py", line 446, in id_group
    rows = self.db(self.table_group().role == role).select()
  File "/home/www-data/web2py/gluon/packages/dal/pydal/objects.py", line 2041, in select
    return adapter.select(self.query, fields, attributes)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 232, in select
    return self.__select(query, fields, **attributes)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/mongo.py", line 344, in __select
    if self.server_version_major < 2.6:
AttributeError: 'Mongo' object has no attribute 'server_version_major'

(uwsing nginx, uwsgi, emperor, latest web2py from master )

**Comment by mdipierro** [comment]
@gi0baro This seems like a serious issue. Looks like the adapters have a method  _configure_on_first_reconnect
but this method may not be called when it should be. Any idea why?

**Comment by gi0baro** [comment]
@mdipierro seems like the select operation is performed before the first connection to the dbms.

**Comment by mdipierro** [comment]
@gi0baro Do you think this is an error in the user's code or in mydal?

**Comment by gi0baro** [comment]
@mdipierro I can't exclude with 100% confidence an error in pyDAL, but the mixin responsible of calling `_configure_on_first_reconnect` is used in postgres adapter too, so I would expect the same error on that. And right now I have a running deployment with like 2k reqs/min with the latest version and never had such problem :/ 
maybe we should try to understand how @remcoboerma got to perform a select before the connection to the database..
