### ISSUE TITLE
Scheduler queue_task dumping json strings into Oracle DB with cx_Oracle

### ISSUE THREAD

**Issue by rich5851** [web2py/web2py#1645]
When following the documentation and setting up scheduler for first time I came across the following error when my tasks started failing.

2017-06-07 23:22:26,785 DEBUG 3040 139872588486464 __init__():158    traceback: Traceback (most recent call last):
  File "/opt/web-apps/web2py/gluon/scheduler.py", line 311, in executor
    args = _decode_list(loads(task.args))
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

After investigation it appears that queue_task is writing dictionary values into oracle DB as string represented JSON in order to save this value as VARCHAR2(512) into the vars and args columns of database  table scheduler_task.

As a work around I have had to put the below trigger on the Oracle database in order to remove the single quotes from the values before insert into the db for any of my tasks to complete. 

create or replace trigger replace_quotes
before insert on SCHEDULER_TASK
for each row
begin
:new.args := replace( :new.args, '''', '' );
:new.vars := replace( :new.vars, '''', '' );
end;
/ 

Versions
2.14.6-stable+timestamp.2016.05.10.00.21.47
(Running on Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips PHP/5.4.16 mod_wsgi/3.4 Python/2.7.5, Python 2.7.5)
cx-Oracle (5.3)
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit

**Comment by mdipierro** [comment]
Are you available to help with some testing? Which version of DAL are you using? I am not convinced this is a bug in the scheduler. Looks like dal adapter is not escaping strings properly.
