### ISSUE TITLE
can't use response.optimize_js in models/db.py, previous version can work

### ISSUE THREAD

**Issue by sugizo** [web2py/web2py#1673]
in models/db.py
response.optimize_js = 'concat,minify,inline'

Traceback (most recent call last):
  File "/Users/MacBookPro/site/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "<string>", line 36, in <module>
  File "/Users/MacBookPro/site/web2py/gluon/globals.py", line 501, in include_files
    time_expire)
  File "/Users/MacBookPro/site/web2py/gluon/cache.py", line 247, in __call__
    value = f()
  File "/Users/MacBookPro/site/web2py/gluon/globals.py", line 496, in call_minify
    self.optimize_js)
  File "/Users/MacBookPro/site/web2py/gluon/contrib/minify/minify.py", line 101, in minify
    contents = read_binary_file(abs_filename)
  File "/Users/MacBookPro/site/web2py/gluon/contrib/minify/minify.py", line 19, in read_binary_file
    f = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/Users/MacBookPro/site/web2py/applications/welcome/static/min.js'

**Comment by leonelcamara** [comment]
Can you provide a simple example we can use to replicate this?

**Comment by ilvalle** [comment]
Tested with latest 2.15.2 and it worked. @sugizo would you test it again?

**Comment by leonelcamara** [comment]
@sugizo managed to replicate it visiting welcome/appadmin/d3_graph_model

Thanks for the bug report sugizo!
