### ISSUE TITLE
Field is already bound to a table when defining tables

### ISSUE THREAD

**Issue by manuelvio** [web2py/web2py#1683]
I'm trying to port my application to web2py 2.15.1 and when I try to run it the error "Field filiale.organization_id is already bound to a table" is raised in a model file.
The significant section is:

```python
db._common_fields.append(Field('organization_id',
                               'reference organization',
                               requires=IS_IN_DB(db, db.organization.id,
                                                 '%(name)s', zero=T('choose one')),
                               default=DEFAULT_TENANT,
                               writable=False,
                               widget=wdg_select2,
                               label=T('Organizzazione')))

db.define_table('filiale',
                Field('codice',
                      type='string'),
                Field('descrizione',
                      type='string',
                      requires=IS_NOT_EMPTY(error_message=T('Inserire una descrizione')),
                      required=True),
                Field('indirizzo',
                      type='string'),
                Field('telefono',
                      type='string'),
                auth.signature,
                format='%(codice)s %(descrizione)s',
                plural='Filiali',
                common_filter=lambda query: db.filiale.organization_id == auth.user.organization_id if 'auth' in session else False)
db.filiale._enable_record_versioning()

db.define_table('coda_assistenza',
                Field('descrizione',
                      type='string',
                      requires=IS_NOT_EMPTY(error_message=T('Inserire una descrizione')),
                      required=True),
                Field('utenti',
                      type='list:reference auth_user',
                      required=False,
                      widget=SQLFORM.widgets.checkboxes.widget,
                      requires=IS_IN_DB(db, db.auth_user.id,
                                        '%(first_name)s %(last_name)s',
                                        zero=T('Seleziona uno o più utenti)'),
                                        multiple=(0, 1000))),
                Field('email_supplementari',
                      type='list:string',
                      notnull=False,
                      required=False,
                      requires=IS_LIST_OF(IS_EMPTY_OR(IS_EMAIL())),
                      label=T("Email Supplementari")),
                Field('coda_default',
                      type='boolean',
                      label=T('Default'),
                      represent=repr_bool,
                      required=True),
                Field('interna',
                      type='boolean',
                      label=T('Interna'),
                      represent=repr_bool,
                      required=True),
                auth.signature,
                format='%(descrizione)s',
                plural=T('Code assistenza'),
                singular=T('Coda assistenza'),
                common_filter=lambda query: db.coda_assistenza.organization_id == auth.user.organization_id if 'auth' in session else False)
db.coda_assistenza._enable_record_versioning()
db.coda_assistenza.utenti.widget = wdg_select2_multiple

```
The traceback:
```
Traceback (most recent call last):
  File "/home/manuel/web2pydist/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/manuel/web2pydist/applications/easytrack/models/db_002_ticket.py", line 236, in <module>
    common_filter=lambda query: db.coda_assistenza.organization_id == auth.user.organization_id if 'auth' in session else False)
  File "/home/manuel/web2pydist/gluon/packages/dal/pydal/base.py", line 587, in define_table
    table = self.lazy_define_table(tablename, *fields, **args)
  File "/home/manuel/web2pydist/gluon/packages/dal/pydal/base.py", line 599, in lazy_define_table
    table = table_class(self, tablename, *fields, **args)
  File "/home/manuel/web2pydist/gluon/packages/dal/pydal/objects.py", line 351, in __init__
    field.bind(self)
  File "/home/manuel/web2pydist/gluon/packages/dal/pydal/objects.py", line 1633, in bind
    'Field %s is already bound to a table' % self.longname)
ValueError: Field filiale.organization_id is already bound to a table
```

Function argument list
```
(self=<pydal.objects.Field object>, table=<Table coda_assistenza (id, descrizione, utenti,...d_by, modified_on, modified_by, organization_id)>)
```

Variables
```
self <pydal.objects.Field object>
self.longname 'filiale.organization_id'
```

The weird thing is that the error refers to the **second** table (coda_assistenza), where there shouldn't be any reference to the field filiale.organization_id since this field it's added as a common field in the first table. Another similar common field is added to the second table, but it should be completely independent from the first one.

This code works fine in version 2.14.6

**Comment by leonelcamara** [comment]
@gi0baro this is a problem in pyDAL correct?

**Comment by rpedroso** [comment]
Probably same issue as #1672

**Comment by roshmee** [comment]
i installed pydal but getting this  error"pyDal' is not recognized as an internal or external command,
operable program or batch file." i donno how to add the pAth for enviroment varaibles.any plzz help
