### ISSUE TITLE
Adapter not found for imap

### ISSUE THREAD

**Issue by jpsteil** [web2py/web2py#1694]
Here is my traceback

Traceback (most recent call last):
 File "C:\dev\web2py\gluon\restricted.py", line 219, in restricted
 exec(ccode, environment)
 File "C:/dev/web2py/applications/wrighthub/models/db.py", line 38, in <module>
 imapdb = DAL('imap://catchall:2007j0j7&@23.253.201.164:993')
 File "C:\dev\web2py\gluon\packages\dal\pydal\base.py", line 170, in __call__
 obj = super(MetaDAL, cls).__call__(*args, **kwargs)
 File "C:\dev\web2py\gluon\packages\dal\pydal\base.py", line 454, in __init__
 adapter = adapters.get_for(self._dbname)
 File "C:\dev\web2py\gluon\packages\dal\pydal\adapters\__init__.py", line 20, in get_for
 'Adapter not found for %s' % uri
SyntaxError: Adapter not found for imap
web2py™ Version 2.15.2-stable+timestamp.2017.07.19.12.18.41

Got a reply on the user group from Anthony stating that support was lost during some move to pydal contrib lib.  Suggested opening a ticket.  Should it be here or for pydal?

-Jim

**Comment by ilvalle** [comment]
See https://groups.google.com/d/topic/web2py-developers/CzjsjXpA78s/discussion
At the moment the imap adapter is here https://github.com/web2py/pydal/blob/master/pydal/contrib/imap_adapter.py. However mind that is neither maintained nor tested. 
It's better to close this ticket and open one in pydal.
