### ISSUE TITLE
psycopg2.ProgrammingError : column does not exist

### ISSUE THREAD

**Issue by manuelvio** [web2py/web2py#1697]
When I try to run my application in web2py 2.15.2 I encounter this issue:

```
<class 'psycopg2.ProgrammingError'> column organization.emailAttivita does not exist LINE 1: ... "organization"."telefono", "organization"."fax", "organizat... ^
```

The traceback is:

```
Traceback (most recent call last):
  File "/home/manuel/web2pydist/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/manuel/web2pydist/applications/easytrack/models/menu.py", line 35, in <module>
    URL('organizzazione', 'set_curr_org', args=[org.id])) for org in db(db.organization.name == False).select()
  File "/home/manuel/web2pydist/gluon/packages/dal/pydal/objects.py", line 2211, in select
    return adapter.select(self.query, fields, attributes)
  File "/home/manuel/web2pydist/gluon/packages/dal/pydal/adapters/base.py", line 760, in select
    return self._select_aux(sql, fields, attributes, colnames)
  File "/home/manuel/web2pydist/gluon/packages/dal/pydal/adapters/base.py", line 716, in _select_aux
    rows = self._select_aux_execute(sql)
  File "/home/manuel/web2pydist/gluon/packages/dal/pydal/adapters/base.py", line 710, in _select_aux_execute
    self.execute(sql)
  File "/home/manuel/web2pydist/gluon/packages/dal/pydal/adapters/__init__.py", line 67, in wrap
    return f(*args, **kwargs)
  File "/home/manuel/web2pydist/gluon/packages/dal/pydal/adapters/base.py", line 410, in execute
    rv = self.cursor.execute(command, *args[1:], **kwargs)
ProgrammingError: column organization.emailAttivita does not exist
LINE 1: ... "organization"."telefono", "organization"."fax", "organizat...
```

My model is:

```python
db.define_table('organization', 
                Field('name',
                      type='string',
                      required=True,
                      unique=True,
                      label=T('name'),
                      requires=IS_NOT_IN_DB(db, 'organization.name')),
                Field('ragione_sociale',
                      label=T('Ragione sociale'),
                      type='string',
                      required=False),
                Field('partita_iva',
                      label=T('Partita IVA'),
                      type='string',
                      required=False),
                Field('indirizzo',
                      label=T('Indirizzo'),
                      type='string',
                      required=False),
                Field('localita',
                      label=T('Località'),
                      type='string',
                      required=False),
                Field('telefono',
                      label=T('Telefono'),
                      type='string',
                      required=False),
                Field('fax',
                      label=T('Fax'),
                      type='string',
                      required=False),
                Field('emailAttivita',
                      label=T('emailAttivita'),
                      type='list:string',
                      requires=IS_LIST_OF(IS_EMPTY_OR(IS_EMAIL())),
                      comment='Elenco di indirizzi email contattati in caso di attività'),
                Field('sistema',
                      label=T('org sistema'),
                      type='boolean',
                      default=False,
                      represent=lambda v, r: I(' ', _class='fa %s' % ('fa-check' if v else '')),
                      comment='Organizzazione di sistema'),
                Field('cliente',
                      label=T('Cliente'),
                      type='boolean',
                      default=False,
                      required=False,
                      represent=lambda v, r: I(' ', _class='fa %s' % ('fa-check' if v else '')),
                      ),
                Field('fornitore',
                      label=T('Fornitore'),
                      type='boolean',
                      default=False,
                      required=False,
                      represent=lambda v, r: I(' ', _class='fa %s' % ('fa-check' if v else '')),
                      ),
                format='%(name)s',
                plural='Organizzazioni'
                )
```
The code portion which raises that error is:

```python
clienti = [
            (I(_class="fa fa-bank") + SPAN(org.name), False, 
                URL('organizzazione', 'set_curr_org', args=[org.id])) for org in db(db.organization.name == False).select()
          ]
```

I printed out what the SELECT statement would look like and this is the result:

```sql
SELECT "organization"."id", "organization"."name", "organization"."ragione_sociale", "organization"."partita_iva", "organization"."indirizzo", "organization"."localita", "organization"."telefono", "organization"."fax", "organization"."emailAttivita", "organization"."sistema", "organization"."cliente", "organization"."fornitore" FROM "organization" WHERE ("organization"."name" = 'False');
```

This is the same select(), but in web2py 2.14.6:

```sql
SELECT  organization.id, organization.name, organization.ragione_sociale, organization.partita_iva, organization.indirizzo, organization.localita, organization.telefono, organization.fax, organization.emailAttivita, organization.sistema, organization.cliente, organization.fornitore FROM organization WHERE (organization.name = 'False');
```

Please note the new presence of the quotation marks that force postgres to look for **organization.emailAttivita** column, which it has been created instead as **organization.emailattivita** by the original migration:

```
                                     Table "public.organization"
     Column      |          Type          |                         Modifiers                         
-----------------+------------------------+-----------------------------------------------------------
 id              | integer                | not null default nextval('organization_id_seq'::regclass)
 name            | character varying(512) | 
 emailattivita   | text[]                 | 
 sistema         | character(1)           | 
 fax             | character varying(512) | 
 indirizzo       | character varying(512) | 
 ragione_sociale | character varying(512) | 
 partita_iva     | character varying(512) | 
 telefono        | character varying(512) | 
 localita        | character varying(512) | 
 fornitore       | character(1)           | 
 cliente         | character(1)           | 
```

**A workaround exists**: setting the `rname` value as 'emailattivita' in the field constructor leads to this SELECT (which works):

```sql
SELECT "organization"."id", "organization"."name", "organization"."ragione_sociale", "organization"."partita_iva", "organization"."indirizzo", "organization"."localita", "organization"."telefono", "organization"."fax", "organization".emailattivita, "organization"."sistema", "organization"."cliente", "organization"."fornitore" FROM "organization" WHERE ("organization"."name" = 'False');
```

Does this issue depend on an adapter (or psycopg) update?

**Comment by BuhtigithuB** [comment]
Maybe your database is not in sync with web2py models?? Please come over
google groups of web2py-users for such type of question...

If you have made change of database, your models may have not been created
in this new database, because web2py think he already created them... In
this case you need to migrate_fake=True and migrate=False for one turn,
then migrate=True and fake_migrate=False... Or you may have had columns to
your table without migrate the change, in that case you have to set
migrate=True over the model table in question and give a look over the
database connection string to make sure you didn't set migrate_all=False...
Switch it to True will allow table migration for all table for which you
have not expressly set migrate=False

Doc here :
http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#markmin_table_migrations

**Comment by leonelcamara** [comment]
I think it's a bad idea to use case insentitivity. Still, you can disable the quotes by setting entity_quoting=False. In your DAL declaration.

**Comment by manuelvio** [comment]
@BuhtigithuB : I have not made any change to the db. I simply updated web2py and run my application. 
@leonelcamara: I didn't mean to use case insensitivity, and I agree that could be a bad idea, but it was defined this way the first time and web2py simply behave correctly until now.
I guess the DAL signature changed its default parameter in the last release? I see now in the group that there was a firebird related post with a similar issue: https://groups.google.com/d/msg/web2py/ooZKk5i8zew/IF91_QMvCQAJ

How was I supposed to know this before I tried the new release with my application?

**Comment by BuhtigithuB** [comment]
You update from which version... As Leonel mention, you may not use case
sensitive field, and there is reserved word too, that been added in web2py
at some point, so it may related to this too...

**Comment by leonelcamara** [comment]
> How was I supposed to know this before I tried the new release with my application?

@manuelvio you have a point there. One could say this was a bug in pyDAL and the fix is creating these problems. I would leave entity_quoting as is and simply change the name in the application code to not use camelcase which is not very pythonic anyway.

**Comment by manuelvio** [comment]
@BuhtigithuB I clearly stated that the last known web2py version which worked with my application was 2.14.6. And the field name wasn't even close to a reserved word. 
We're talking about quotes being added automatically in queries, as I said from the beginning. 
@leonelcamara whether the lack of quotation was a bug or not I think that changing a default value in a constructor was a change worth noticing to final users. That said, I agree that camelcase is not very pythonic, but I think I'm reverting to old behaviour for now, and considering a refactoring in the future.

**Comment by BouchaaraAdil** [comment]
try those commands
```
./manage.py db upgrade
./manage.py db migrate
```
