### ISSUE TITLE
XML sanitize=True throws error on check for acceptable url in py2

### ISSUE THREAD

**Issue by lkrn** [web2py/web2py#1724]
Below code in view throws error
```
{{=XML('<img src="/myapp/static/images/pict.jpg" />', sanitize=True)}}
```

Error:
```
Traceback (most recent call last):
  File "\web2py\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "<string>", line 73, in <module>
  File "\web2py\gluon\html.py", line 603, in __init__
    text = sanitizer.sanitize(text, permitted_tags, allowed_attributes)
  File "\web2py\gluon\sanitizer.py", line 219, in sanitize
    allowed_attributes=allowed_attributes).strip(text, escape)
  File "\web2py\gluon\sanitizer.py", line 170, in strip
    self.feed(rawstring)
  File "HTMLParser.py", line 117, in feed
  File "HTMLParser.py", line 161, in goahead
  File "HTMLParser.py", line 325, in parse_starttag
  File "HTMLParser.py", line 407, in handle_startendtag
  File "\web2py\gluon\sanitizer.py", line 115, in handle_starttag
    if self.url_is_acceptable(attrs[attribute]):
  File "\web2py\gluon\sanitizer.py", line 148, in url_is_acceptable
    parsed = urlparse(url)
TypeError: 'module' object is not callable
```

Environment info:
- platform: win32
- python: 2.7.9 (major=2, minor=7, micro=9, releaselevel='final', serial=0)
- web2py: 2.15.2-stable+timestamp.2017.07.19.12.18.41

Steps to reproduce:
1. Open web2py from console
2. Try execute: `XML('<img src="/myapp/static/images/pict.jpg" />', sanitize=True)`

Possible fix:
In gluon._compat.py change line 14 from:
`import urlparse`
to 
`from urlparse import urlparse`

**Comment by ilvalle** [comment]
Don't change _compat, instead change urlparse in urlparse.urlparse in sanitizer.py, would you post a PR?

**Comment by lkrn** [comment]
hm, but for py3 (else block in _compat) actually a function is imported:
`from urllib import parse as urlparse`
Given this, won't urlparse.urlparse in sanitizer.py throw an error in case of py3?

**Comment by leonelcamara** [comment]
@lkrn if you pay close attention that's not a function :) that's the parse module in urllib.

**Comment by lkrn** [comment]
@leonelcamara thanks
@ilvalle PR submitted

**Comment by ilvalle** [comment]
Well done. If you can, add also an unittest with the example you posted here. Il 10 ago 2017 6:58 AM, Alex Burdin <notifications@github.com> ha scritto:@leonelcamara thanks
@ilvalle PR submitted
