### ISSUE TITLE
<type 'exceptions.MemoryError'> from appadmin

### ISSUE THREAD

**Issue by benlawraus** [web2py/web2py#1744]
I am trying to view a record such as
https://10.1.10.29/remail/appadmin/update/db/recipient_cc/110898
from the admin UI
Error is:
<type 'exceptions.MemoryError'>

Version
web2py™	Version 2.15.3-stable+timestamp.2017.08.07.07.32.04
Python	Python 2.7.12: /usr/local/bin/uwsgi (prefix: /usr)
Traceback
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "<string>", line 220, in <module>
  File "/home/www-data/web2py/gluon/globals.py", line 427, in write
    self.body.write(to_native(xmlescape(data)))
  File "/home/www-data/web2py/gluon/html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "/home/www-data/web2py/gluon/html.py", line 2182, in xml
    return DIV.xml(newform)
  File "/home/www-data/web2py/gluon/html.py", line 960, in xml
    (fa, co) = self._xml()
  File "/home/www-data/web2py/gluon/html.py", line 952, in _xml
    co = b''.join([xmlescape(component) for component in self.components])
  File "/home/www-data/web2py/gluon/html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "/home/www-data/web2py/gluon/html.py", line 960, in xml
    (fa, co) = self._xml()
  File "/home/www-data/web2py/gluon/html.py", line 952, in _xml
    co = b''.join([xmlescape(component) for component in self.components])
  File "/home/www-data/web2py/gluon/html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "/home/www-data/web2py/gluon/html.py", line 960, in xml
    (fa, co) = self._xml()
  File "/home/www-data/web2py/gluon/html.py", line 952, in _xml
    co = b''.join([xmlescape(component) for component in self.components])
  File "/home/www-data/web2py/gluon/html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "/home/www-data/web2py/gluon/html.py", line 960, in xml
    (fa, co) = self._xml()
  File "/home/www-data/web2py/gluon/html.py", line 952, in _xml
    co = b''.join([xmlescape(component) for component in self.components])
  File "/home/www-data/web2py/gluon/html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "/home/www-data/web2py/gluon/html.py", line 1930, in xml
    return DIV.xml(self)
  File "/home/www-data/web2py/gluon/html.py", line 960, in xml
    (fa, co) = self._xml()
  File "/home/www-data/web2py/gluon/html.py", line 952, in _xml
    co = b''.join([xmlescape(component) for component in self.components])
  File "/home/www-data/web2py/gluon/html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "/home/www-data/web2py/gluon/html.py", line 960, in xml
    (fa, co) = self._xml()
  File "/home/www-data/web2py/gluon/html.py", line 949, in _xml
    fa += (b' %s="%s"') % (to_bytes(name), xmlescape(value, True))
  File "/home/www-data/web2py/gluon/html.py", line 133, in xmlescape
    data = local_html_escape(data, quote)
  File "/home/www-data/web2py/gluon/utils.py", line 450, in local_html_escape
    import cgi
  File "/home/www-data/web2py/gluon/custom_import.py", line 111, in custom_importer
    return NATIVE_IMPORTER(name, globals, locals, fromlist, level)
MemoryError
Error snapshot  help
<type 'exceptions.MemoryError'>()

inspect attributes

Frames

File /home/www-data/web2py/gluon/restricted.py in restricted at line 219 code arguments variables

File /home/www-data/web2py/<string> in <module> at line 220 code arguments variables

File /home/www-data/web2py/gluon/globals.py in write at line 427 code arguments variables

File /home/www-data/web2py/gluon/html.py in xmlescape at line 125 code arguments variables

File /home/www-data/web2py/gluon/html.py in xml at line 2182 code arguments variables

File /home/www-data/web2py/gluon/html.py in xml at line 960 code arguments variables

File /home/www-data/web2py/gluon/html.py in _xml at line 952 code arguments variables

File /home/www-data/web2py/gluon/html.py in xmlescape at line 125 code arguments variables

File /home/www-data/web2py/gluon/html.py in xml at line 960 code arguments variables

File /home/www-data/web2py/gluon/html.py in _xml at line 952 code arguments variables

File /home/www-data/web2py/gluon/html.py in xmlescape at line 125 code arguments variables

File /home/www-data/web2py/gluon/html.py in xml at line 960 code arguments variables

File /home/www-data/web2py/gluon/html.py in _xml at line 952 code arguments variables

File /home/www-data/web2py/gluon/html.py in xmlescape at line 125 code arguments variables

File /home/www-data/web2py/gluon/html.py in xml at line 960 code arguments variables

File /home/www-data/web2py/gluon/html.py in _xml at line 952 code arguments variables

File /home/www-data/web2py/gluon/html.py in xmlescape at line 125 code arguments variables

File /home/www-data/web2py/gluon/html.py in xml at line 1930 code arguments variables

File /home/www-data/web2py/gluon/html.py in xml at line 960 code arguments variables

File /home/www-data/web2py/gluon/html.py in _xml at line 952 code arguments variables

File /home/www-data/web2py/gluon/html.py in xmlescape at line 125 code arguments variables

File /home/www-data/web2py/gluon/html.py in xml at line 960 code arguments variables

File /home/www-data/web2py/gluon/html.py in _xml at line 949 code arguments variables

File /home/www-data/web2py/gluon/html.py in xmlescape at line 133 code arguments variables

File /home/www-data/web2py/gluon/utils.py in local_html_escape at line 450 code arguments variables

File /home/www-data/web2py/gluon/custom_import.py in custom_importer at line 111 code arguments variables

Function argument list

(name='cgi', globals={'AES_dec': <function AES_dec>, 'AES_enc': <function AES_enc>, 'AES_new': <function AES_new>, 'DIGEST_ALG_BY_SIZE': {32: 'md5', 40: 'sha1', 56: 'sha224', 64: 'sha256', 96: 'sha384', 128: 'sha512'}, 'HAVE_AES': False, 'HAVE_COMPARE_DIGEST': True, 'HAVE_PBKDF2': True, 'HAVE_URANDOM': True, 'PY2': True, 'PYAES': <module 'gluon.contrib.pyaes' from '/home/www-data/web2py/gluon/contrib/pyaes/__init__.pyc'>, ...}, locals={}, fromlist=[], level=-1)

**Comment by leonelcamara** [comment]
You ran out of memory. What system are you running this on?

**Comment by dalaka** [comment]
Am using ubuntu 16.04 with 64bit, I am experiencing the same issue

**Comment by leonelcamara** [comment]
There's probably some kind of infinite recursion going on.
