### ISSUE TITLE
Print statement fails in command line script (v2.15.3)

### ISSUE THREAD

**Issue by iiijjjii** [web2py/web2py#1750]
After upgrading to v2.15.3, when scripts are run from the command line, print statements produce a SyntaxError. The print function works. This was not a problem in v2.14.6. (Tested with Python 2.7.11)

To illustrate:

    $ cat test.py
    #!/usr/bin/env python
    if __name__ == '__main__':
        print 'Hello!'

    $ python web2py.sh --no-banner -S myapp -R test.py
    Traceback (most recent call last):
      File "/srv/http/web2py/2.15.3/web2py/gluon/shell.py", line 270, in run
        execfile(startfile, _env)
      File "/root/tmp/test.py", line 4
        print 'abc'
    SyntaxError: invalid syntax

This works:

    $ cat test2.py
    #!/usr/bin/env python
    if __name__ == '__main__':
        print('Hello!')

    $ python web2py.py --no-banner -S myapp -R test2.py
    Hello!

This isn't a huge problem but it does break backwards compatibility.

**Comment by abastardi** [comment]
As noted [here](https://groups.google.com/d/msg/web2py/xvObm3bdyhU/_P0TgpAwAAAJ), this happens because `gluon.shell.py` now includes `from __future__ import print_function`, so any code run through the web2py command line (including within the web2py shell) will be forced to use the `print()` function rather than the `print` statement.
