### ISSUE TITLE
Bug:  upload field whose filename is cutoff  by length="some even value" will raise "Odd-length string"  when I click the field link under the SQLFORM.smartgrid view

### ISSUE THREAD

**Issue by liuyibing45** [web2py/web2py#1771]
windows 10 or server 2012 r2(can both reproduce the bug), python 3.6, web2py 2.15.4.
I define a table in db.py as following:
`db.define_table('table_up_file',
                Field('input_year', 'string',default=request.now.strftime("%Y")),
                Field('up_file', 'upload',length=200,autodelete=True), )`
In default controller I use the following code
`query=db.table_up_file.id>0
grid=SQLFORM.smartgrid(db.table_up_file,
                           constraints=dict(table_up_file=query))
return dict(grid=grid)`
I uploaded a file with SQLFORM successfully. The uploaded filename is longer than the length limit which is ruled in the db.py. So the filename is cut off. But when click the field link under the grid view which is returned by the SQLFORM.smartgrid() function, I got the following error infos:

Traceback (most recent call last):
  File "D:\web2py\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "D:/web2py/applications/soma/controllers/default.py", line 2048, in <module>
  File "D:\web2py\gluon\globals.py", line 414, in <lambda>
    self._caller = lambda f: f()
  File "D:\web2py\gluon\tools.py", line 3981, in f
    return action(*a, **b)
  File "D:/web2py/applications/soma/controllers/default.py", line 555, in school_upload_file
    constraints=dict(table_up_file=query)
  File "D:\web2py\gluon\sqlhtml.py", line 3235, in smartgrid
    user_signature=user_signature, **kwargs)
  File "D:\web2py\gluon\sqlhtml.py", line 2384, in grid
    stream = response.download(request, db)
  File "D:\web2py\gluon\globals.py", line 666, in download
    (filename, stream) = field.retrieve(name, nameonly=True)
  File "D:\web2py\gluon\packages\dal\pydal\objects.py", line 1734, in retrieve
    file_properties = self.retrieve_file_properties(name, path)
  File "D:\web2py\gluon\packages\dal\pydal\objects.py", line 1765, in retrieve_file_properties
    filename = base64.b16decode(m.group('name'), True).decode('utf-8')
  **File "C:\Users\liuyibing\AppData\Local\Programs\Python\Python36\lib\base64.py", line 275, in b16decode
    return binascii.unhexlify(s)
binascii.Error: Odd-length string**
After debugging, I change the length limit which is defined in db.py to some odd value, this can solve the problem. I think the length limit of upload fieldname can be either odd or even. So i think this is a bug.

**Comment by liuyibing45** [comment]
a solution:
modify the line 1763-1773  to:
```
        if m.group('name'):
            if m.group('name').__len__() % 2 == 0:
                try:
                    filename = base64.b16decode(m.group('name'), True).decode('utf-8')
                    filename = REGEX_CLEANUP_FN.sub('_', filename)
                except (TypeError, AttributeError):
                    filename = name
            else:
                try:
                    filename = base64.b16decode(m.group('name')+"0", True).decode('utf-8')
                    filename = REGEX_CLEANUP_FN.sub('_', filename)
                except (TypeError, AttributeError):
                    filename = name
```
