### ISSUE TITLE
translator params_substitution fails 

### ISSUE THREAD

**Issue by sherdim** [web2py/web2py#1808]
The error appears in 2.15 in appadmin html template
and have survived after update
it is unicode related IMHO

web2py™ | Version 2.16.1-stable+timestamp.2017.11.14.05.54.25
Python 2.7.11
sys.setdefaultencoding('utf-8')  at sitecustomize.py

To reproduce open link 
/welcome/appadmin/select/db?query=db.auth_user.id>0
with Russian locale

```
Traceback (most recent call last):
  File "C:\a\w2p\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "C:/a/w2p/applications/welcome/views/appadmin.html", line 196, in <module>
    <p>
  File "C:\a\w2p\gluon\globals.py", line 432, in write
    self.body.write(to_native(xmlescape(data)))
  File "C:\a\w2p\gluon\html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "C:\a\w2p\gluon\languages.py", line 431, in xml
    return str(self) if self.M else local_html_escape(str(self), quote=False)
  File "C:\a\w2p\gluon\languages.py", line 391, in __str__
    self.T.translate(self.m, self.s))
  File "C:\a\w2p\gluon\languages.py", line 951, in translate
    return message.translate(ttab_out)
TypeError: character mapping must return integer, None or unicode
```

If to comment out translate calls and to reload the app then

```py
                    else str(value)#.translate(ttab_in)
                    for value in symbols)
            message = self.params_substitution(message, symbols)
        return message#.translate(ttab_out)
```

appadmin works but  texts w params stay encoded like "\x10\x34\x11..."
in place of the message  (string from /welcome/languages/ru.py)
`'%s selected': '%%{!выбрана[0]} %s %%{запись[0]}',`

So encoded translated text fails to be translated back.

If to remove /welcome/languages/ru.py then the error disappears.
The message is simply:
`0 selected`

**Comment by tyrbonit** [comment]
1. Strings in plural-ru.py file is uncorrect:
the content plural-ru.py should be
```
# -*- coding: utf-8 -*-
{
'выбрана': ['выбраны','выбрано'],
'год': ['года','лет'],
'день': ['дня','дней'],
'запись': ['записи','записей'],
'изменена': ['изменены','изменено'],
'месяц': ['месяца','месяцев'],
'минуту': ['минуты','минут'],
'неделю': ['недели','недель'],
'секунду': ['секунды','секунд'],
'строка': ['строки','строк'],
'удалена': ['удалены','удалено'],
'час': ['часа','часов'],
}
```
instead
```
# -*- coding: utf-8 -*-
{
'выбрана': ['\\xd0\\xb2\\xd1\\x8b\\xd0\\xb1\\xd1\\x80\\xd0\\xb0\\xd0\\xbd\\xd1\\x8b', '\\xd0\\xb2\\xd1\\x8b\\xd0\\xb1\\xd1\\x80\\xd0\\xb0\\xd0\\xbd\\xd0\\xbe'],
'год': ['\\xd0\\xb3\\xd0\\xbe\\xd0\\xb4\\xd0\\xb0', '\\xd0\\xbb\\xd0\\xb5\\xd1\\x82'],
'день': ['\\xd0\\xb4\\xd0\\xbd\\xd1\\x8f', '\\xd0\\xb4\\xd0\\xbd\\xd0\\xb5\\xd0\\xb9'],
'запись': ['\\xd0\\xb7\\xd0\\xb0\\xd0\\xbf\\xd0\\xb8\\xd1\\x81\\xd0\\xb8', '\\xd0\\xb7\\xd0\\xb0\\xd0\\xbf\\xd0\\xb8\\xd1\\x81\\xd0\\xb5\\xd0\\xb9'],
'изменена': ['\\xd0\\xb8\\xd0\\xb7\\xd0\\xbc\\xd0\\xb5\\xd0\\xbd\\xd0\\xb5\\xd0\\xbd\\xd1\\x8b', '\\xd0\\xb8\\xd0\\xb7\\xd0\\xbc\\xd0\\xb5\\xd0\\xbd\\xd0\\xb5\\xd0\\xbd\\xd0\\xbe'],
'месяц': ['\\xd0\\xbc\\xd0\\xb5\\xd1\\x81\\xd1\\x8f\\xd1\\x86\\xd0\\xb0', '\\xd0\\xbc\\xd0\\xb5\\xd1\\x81\\xd1\\x8f\\xd1\\x86\\xd0\\xb5\\xd0\\xb2'],
'минуту': ['\\xd0\\xbc\\xd0\\xb8\\xd0\\xbd\\xd1\\x83\\xd1\\x82\\xd1\\x8b', '\\xd0\\xbc\\xd0\\xb8\\xd0\\xbd\\xd1\\x83\\xd1\\x82'],
'неделю': ['\\xd0\\xbd\\xd0\\xb5\\xd0\\xb4\\xd0\\xb5\\xd0\\xbb\\xd0\\xb8', '\\xd0\\xbd\\xd0\\xb5\\xd0\\xb4\\xd0\\xb5\\xd0\\xbb\\xd1\\x8c'],
'секунду': ['\\xd1\\x81\\xd0\\xb5\\xd0\\xba\\xd1\\x83\\xd0\\xbd\\xd0\\xb4\\xd1\\x8b', '\\xd1\\x81\\xd0\\xb5\\xd0\\xba\\xd1\\x83\\xd0\\xbd\\xd0\\xb4'],
'строка': ['\\xd1\\x81\\xd1\\x82\\xd1\\x80\\xd0\\xbe\\xd0\\xba\\xd0\\xb8', '\\xd1\\x81\\xd1\\x82\\xd1\\x80\\xd0\\xbe\\xd0\\xba'],
'удалена': ['\\xd1\\x83\\xd0\\xb4\\xd0\\xb0\\xd0\\xbb\\xd0\\xb5\\xd0\\xbd\\xd1\\x8b', '\\xd1\\x83\\xd0\\xb4\\xd0\\xb0\\xd0\\xbb\\xd0\\xb5\\xd0\\xbd\\xd0\\xbe'],
'час': ['\\xd1\\x87\\xd0\\xb0\\xd1\\x81\\xd0\\xb0', '\\xd1\\x87\\xd0\\xb0\\xd1\\x81\\xd0\\xbe\\xd0\\xb2'],
}
```

2. You must modify the following functions in languages.py, because its return not encoded string ():

```
def upper_fun(s):
    return to_bytes(to_unicode(s).upper())


def title_fun(s):
    return to_bytes(to_unicode(s).title())


def cap_fun(s):
    return to_bytes(to_unicode(s).capitalize())
```
