### ISSUE TITLE
python3.5 : AttributeError: module 'urllib' has no attribute 'quote_plus'

### ISSUE THREAD

**Issue by veiko99** [web2py/web2py#1822]
python 3.5, web2py version 2.16.1-stable+timestamp.2017.11.14.05.54.25

```
ERROR:Rocket.Errors.Thread-4:Traceback (most recent call last):

  File "/home/web2py/gluon/rocket.py", line 1319, in run
    self.run_app(conn)

  File "/home/web2py/gluon/rocket.py", line 1820, in run_app
    output = self.app(environ, self.start_response)

  File "/home/web2py/gluon/main.py", line 650, in app_with_logging
    ret[0] = wsgiapp(environ, responder2)

  File "/home/web2py/gluon/main.py", line 559, in wsgibase
    http_response, request, environ, ticket)

  File "/home/web2py/gluon/rewrite.py", line 238, in try_rewrite_on_error
    (status, ticket, urllib.quote_plus(

AttributeError: module 'urllib' has no attribute 'quote_plus'
```

**Comment by Cindyleeeeee** [comment]
quote_plus is now included in parse.
Use urllib.parse.quote_plus().

**Comment by mbratch** [comment]
> Use urllib.parse.quote_plus().

Error:  module 'urllib' has no attribute 'parse'
