### ISSUE TITLE
is this a super bug in scheduler in version web2py.2.14.6 ?

### ISSUE THREAD

**Issue by liuzhijun** [web2py/web2py#1827]
Traceback (most recent call last):
  File "/home/www-data/web2py2000/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "applications/player/models/0.py", line 83, in <module>
    scheduler = Scheduler(session_service.db, migrate=False)
  File "/home/www-data/web2py2000/gluon/scheduler.py", line 585, in __init__
    self.define_tables(db, migrate=migrate)
  File "/home/www-data/web2py2000/gluon/scheduler.py", line 653, in define_tables
    migrate=self.__get_migrate('scheduler_task', migrate),
  File "/home/www-data/web2py2000/gluon/packages/dal/pydal/base.py", line 819, in define_table
    raise SyntaxError('table already defined: %s' % tablename)
SyntaxError: table already defined: scheduler_task

**Comment by liuzhijun** [comment]
but it works well on windows, kindly help, thank you!

**Comment by liuzhijun** [comment]
the problem was fixed by add a condition when init scheduler_instance, like:
`if not hasattr(current, "scheduler"):
    from gluon.scheduler import Scheduler
    scheduler = Scheduler(session_service.db, migrate=False)
    current.scheduler = scheduler`
