### ISSUE TITLE
<type 'exceptions.TypeError'> all_envelopes() takes no arguments (1 given)

### ISSUE THREAD

**Issue by A-um** [web2py/web2py#1830]
Hello, just writing to report a possible bug with web2py 2.16.1 stable. 

This error appears which does not appear in the 2.14.6 stable version of Web2py. I am not sure which information I should post in order to demonstrate and make the debugging easier so here is the function regarding the error message and the traceback.

```
@service.json    
def all_envelopes():
    # DISPLAY ALL ENVELOPES #
    userID = str(request.get_vars["userID"])    
    post = db((db.envelopes.userID == userID)).select(db.envelopes.ALL, orderby=db.envelopes.title)
    count = db((db.envelopes.userID == userID)).count()
    return dict(maxRows=count, data=post)
```

```
Traceback (most recent call last):
  File "C:\Users\Kalipso\Desktop\web2py\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "C:/Users/Kalipso/Desktop/web2py/applications/envelopes/controllers/default.py", line 727, in <module>
  File "C:\Users\Kalipso\Desktop\web2py\gluon\globals.py", line 419, in <lambda>
    self._caller = lambda f: f()
  File "C:/Users/Kalipso/Desktop/web2py/applications/envelopes/controllers/default.py", line 725, in call
    return service()
  File "C:\Users\Kalipso\Desktop\web2py\gluon\tools.py", line 5481, in __call__
    return self.serve_json(request.args[1:])
  File "C:\Users\Kalipso\Desktop\web2py\gluon\tools.py", line 5165, in serve_json
    s = self.call_service_function(self.json_procedures[args[0]], *args[1:], **d)
  File "C:\Users\Kalipso\Desktop\web2py\gluon\tools.py", line 5506, in call_service_function
    return f(*a, **b)
TypeError: all_envelopes() takes no arguments (1 given)
```

**Comment by dartg** [comment]
When using services, GET-vars are translated to function arguments. Since you're expecting `userID`, your funcion should look like:

```
@service.json    
def all_envelopes(userID):
    # DISPLAY ALL ENVELOPES #
    post = db((db.envelopes.userID == userID)).select(db.envelopes.ALL, orderby=db.envelopes.title)
    count = db((db.envelopes.userID == userID)).count()
    return dict(maxRows=count, data=post)
```
