### ISSUE TITLE
<type 'exceptions.AttributeError'> 'NoneType' object has no attribute '_tablename'

### ISSUE THREAD

**Issue by john11721** [web2py/web2py#1836]
https://github.com/web2py/web2py/issues/1836

**Comment by john11721** [comment]
**CODE:**
    rows = db(db.stocks).select('Date_','VTI','VBIAX','VDADX','VIGAX','VTSAX','VFIAX','VGSLX','FCYIX','DVN','GOOG','GOOGL','MET','DIA','VTIAX','FCNTX')
    return locals()

**Comment by john11721** [comment]
Version 2.16.1-stable+timestamp.2017.11.14.05.54.25

Traceback (most recent call last):
  File "F:\web2py\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "F:\web2py\applications\impstocks\views\default/index.html", line 82, in <module>
  File "F:\web2py\gluon\globals.py", line 432, in write
    self.body.write(to_native(xmlescape(data)))
  File "F:\web2py\gluon\html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "F:\web2py\gluon\html.py", line 960, in xml
    (fa, co) = self._xml()
  File "F:\web2py\gluon\html.py", line 952, in _xml
    co = b''.join([xmlescape(component) for component in self.components])
  File "F:\web2py\gluon\html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "F:\web2py\gluon\packages\dal\pydal\objects.py", line 2536, in xml
    rv = self.db.represent('rows_xml', self)
  File "F:\web2py\gluon\packages\dal\pydal\base.py", line 833, in represent
    return self.representers[name](*args, **kwargs)
  File "F:\web2py\gluon\sqlhtml.py", line 3433, in __init__
    tablemap = dict(((f.tablename, f.table) if isinstance(f, Field) else (f._table._tablename, f._table) for f in fieldmap.values()))
  File "F:\web2py\gluon\sqlhtml.py", line 3433, in <genexpr>
    tablemap = dict(((f.tablename, f.table) if isinstance(f, Field) else (f._table._tablename, f._table) for f in fieldmap.values()))
AttributeError: 'NoneType' object has no attribute '_tablename'

**Comment by dartg** [comment]
Could you please explain and post the full code?

**Comment by john11721** [comment]
[Code for  (#1836).txt](https://github.com/web2py/web2py/files/1755672/Code.for.1836.txt)
[output.xlsx](https://github.com/web2py/web2py/files/1755674/output.xlsx)

**Comment by john11721** [comment]
This code works on Linux using the following link which I am running a back leveled version of web2py
2.14.6-stable+timestamp.2016.05.10.00.21.47
https://john11721.pythonanywhere.com/impstocks18/default/index

On windows 10 where it fails  I am running Version 2.16.1-stable+timestamp.2017.11.14.05.54.25

[output.csv.txt](https://github.com/web2py/web2py/files/1755685/output.csv.txt)
The attached output.csv file gets loaded into the data base

The code file  Code for (#1836).txt is attached above 
ignore file output.xlsx that should have been the CSV file

The following line of code is where it fails:
rows = db(db.stocks).select('Date_','VTI','VBIAX','VDADX','VIGAX','VTSAX','VFIAX','VGSLX','FCYIX','DVN','GOOG','GOOGL','MET','DIA','VTIAX','FCNTX')
return locals()

**Comment by dburba** [comment]
The same issue as #1819

**Comment by dartg** [comment]
I can't reproduce the issue, not at least using the following definition:

```
db.define_table('stocks',
    Field('Date_', 'string'),
    Field('VTI', 'float'),
    Field('VBIAX', 'float'),
    Field('VDADX', 'float'),
    Field('VIGAX', 'float'),
    Field('VTSAX', 'float'),
    Field('VFIAX', 'float'),
    Field('VGSLX', 'float'),
    Field('FCYIX', 'float'),
    Field('DVN', 'float'),
    Field('GOOG', 'float'),
    Field('GOOGL', 'float'),
    Field('MET', 'float'),
    Field('DIA', 'float'),
    Field('VTIAX', 'float'),
    Field('FCNTX', 'float'))
```

Do you have any extra code or virtual fields? Are you sure the select is failing?

**Comment by john11721** [comment]
my code works when I run under PythonAnywhere  with web2py at **2.14.6-**stable+timestamp.2016.05.10.00.21.47

The problem is when I try running on **windows 10**  using the current windows binary for
 web2py ****Version 2.16.1-stable+timestamp.2017.11.14.05.54.25****

I created another instance of pythonanywhere and tried to install  Version 2.16.1but it fails(expermential)

**is it possible to to get an old windows binary for 2.14.6?**
 I did try building from source several months ago but had no luck 

Other thoughts:
I believe I read some time back that Massimo Di Pierro said that PYDAL/DAL had moved out of web2py 
if that true do you know what version of web2py  that happened under


**### dburba** 
are you running on linux or windows 10?

**Comment by dburba** [comment]
I am on linux
