### ISSUE TITLE
Import html.parser error Python3

### ISSUE THREAD

**Issue by romicasal** [web2py/web2py#1912]
Hello! I updated to the latest version [Python 3.5 Web2py 2.16.1] and got the following error

Traceback (most recent call last):
  File "/..../web2py/gluon/__init__.py", line 23, in <module>
    import pydal
  File "/..../web2py/gluon/packages/dal/pydal/__init__.py", line 3, in <module>
    from .base import DAL
  File "/..../web2py/gluon/packages/dal/pydal/base.py", line 146, in <module>
    from .objects import Table, Field, Rows, Row, Set
  File "/..../web2py/gluon/packages/dal/pydal/objects.py", line 4, in <module>
    import cgi
  File "/usr/lib/python3.5/cgi.py", line 42, in <module>
    import html
  File "/..../web2py/gluon/html.py", line 21, in <module>
    from gluon import sanitizer, decoder
  File "/..../web2py/gluon/sanitizer.py", line 13, in <module>
    from gluon._compat import HTMLParser, urlparse, entitydefs, basestring
  File "/..../web2py/gluon/_compat.py", line 83, in <module>
    from html.parser import HTMLParser
ImportError: No module named 'html.parser'; 'html' is not a package

**Comment by leonelcamara** [comment]
This isn't a web2py bug, it's a name collision, you probably have an html.py somewhere.

**Comment by Netease-163** [comment]
> This isn't a web2py bug, it's a name collision, you probably have an html.py somewhere.

Yes The html.py file is located in WEB2PY/gluon
the code "from html.parser import HTMLParser" in WEB2PY/gluon/_compat.py should import from the build_in package html(Located in python36/lib )
But the in sys.path, "WEB2PY/gluon" is prior to “python36/lib”
so it will import the html pack in  "WEB2PY/gluon/html.py" instead of  “python36/lib/html/__init__.py”

Solution:
insert the following code before "from html.parser import HTMLParser" in WEB2PY/gluon/_compat.py

```
    print(sys.path)
    for p in sys.path:
        if p.endswith('gluon'):
            pf=p
        else:
            fp=None
    if pf:
        sys.path.remove(pf)
        sys.path.append(pf)
    print(sys.path)
```
