### ISSUE TITLE
ImportError: No module named patch while importing Modules in scheduler.

### ISSUE THREAD

**Issue by smrutim01** [web2py/web2py#1968]
I have a couple of modules in the Modules directory.

viz:
`CustomSSH.py`

Within it I have defined a lot of functions.

I want to use those functions in the Scheduler file.

I have imported those modules in the Scheduler using 

`CustomSSH =  local_import('CustomSSH ') `

But when I start the scheduler I see the below error.

```
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2018
Version 2.15.4-stable+timestamp.2017.09.02.04.02.22
Database drivers available: sqlite3, imaplib, pymysql, pg8000
starting single-scheduler for "<app_name>"...
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "applications/<app_name>/models/scheduler.py", line 22, in <module>
    import applications.<app_name>.modules.customSSH as customSSH
  File "/home/www-data/web2py/gluon/custom_import.py", line 111, in custom_importer
    return NATIVE_IMPORTER(name, globals, locals, fromlist, level)
  File "applications/<app_name>/modules/customSSH.py", line 4, in <module>
    import applications.<app_name>.modules.multiprocessing as multiprocessing
  File "/home/www-data/web2py/gluon/custom_import.py", line 111, in custom_importer
    return NATIVE_IMPORTER(name, globals, locals, fromlist, level)
  File "applications/<app_name>/modules/multiprocessing/__init__.py", line 64, in <module>
    import multiprocessing.patch
  File "/home/www-data/web2py/gluon/custom_import.py", line 111, in custom_importer
    return NATIVE_IMPORTER(name, globals, locals, fromlist, level)
ImportError: No module named patch

```

I tried to import the CustomSSH directly into the scheduler, 

`import CustomSSH `

but with no success. Any leads to this would be really helpful.

```
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2018
Version 2.15.4-stable+timestamp.2017.09.02.04.02.22
Database drivers available: sqlite3, imaplib, pymysql, pg8000
starting single-scheduler for "<app_name>"...
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "applications/<app_name>/models/scheduler.py", line 24, in <module>
    import customSSH
  File "/home/www-data/web2py/gluon/custom_import.py", line 104, in custom_importer
    raise ImportError(e1, import_tb)  # there an import error in the module
ImportError: (ImportError('No module named patch',), <traceback object at 0xb5738964>)

```

**Comment by leonelcamara** [comment]
Don't use local_import. Are you using python 2.6? Note that web2py is not compatible with 2.6 anymore. That said, you can make that work by changing that import to be a relative import or by putting that module in web2py/site-packages
