### ISSUE TITLE
db.export_to_csv_file() error with python 3.7

### ISSUE THREAD

**Issue by benlawraus** [web2py/web2py#2013]
**Describe the bug**
db.export_to_csv_file() error with python 3.7
```
TypeError: a bytes-like object is required, not 'str'
```
in
```
web2py/gluon/packages/dal/pydal/base.py", line 844, in export_to_csv_file
    ofile.write('TABLE %s\r\n' % table)
```

**To Reproduce**
```
Bens-iMac:web2py ben$ pipenv run python web2py.py -M -S pacificW
/Users/ben/.local/share/virtualenvs/web2py-6f1t1lX6/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2018
Version 2.17.1-stable+timestamp.2018.08.05.17.57.00
Database drivers available: sqlite3, psycopg2, imaplib, pymysql, pyodbc
WARNING:web2py:import IPython error; use default python shell
Python 3.7.0 (default, Jul 23 2018, 20:22:55) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> db.export_to_csv_file(open('somefile.csv', 'wb'))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/ben/Documents/programs/web2py/gluon/packages/dal/pydal/base.py", line 844, in export_to_csv_file
    ofile.write('TABLE %s\r\n' % table)
TypeError: a bytes-like object is required, not 'str'
>>> 
```

**Comment by RichDijk** [comment]
Running Web2py with Python 3.7.0 on Windows I have the same issue.

```
elements.export_to_csv_file(open('elements.csv', 'wb'))

Traceback (most recent call last):
  File "C:\web2py\web2py\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "C:/web2py/web2py/applications/datamgt/controllers/default.py", line 447, in <module>
  File "C:\web2py\web2py\gluon\globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "C:/web2py/web2py/applications/datamgt/controllers/default.py", line 78, in write_archimate
    open('test.csv', 'wb').write(str(db(db.concept.id).select()))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by leonelcamara** [comment]
This has to do with how you open the files for writing. With python 3 you need to open the file like this

    open('test.csv' 'w', encoding='utf-8', newline='')

instead of:

    open('test.csv', 'wb')

See https://groups.google.com/forum/#!topic/web2py/nFCSyh8o31Q

**Comment by whk** [comment]
and similarly, open('test.csv', 'r', encoding='utf-8', newline='') to restore it
