### ISSUE TITLE
sequence item 0: expected str instance, bytes found when try open some of table in appadmin

### ISSUE THREAD

**Issue by postcoder** [web2py/web2py#2024]
After update web2py

web2py™ | Version 2.17.1-stable+timestamp.2018.08.06.01.02.56
-- | --
Python 3.6.3: /usr/local/bin/uwsgi (prefix: /usr)

Can't open no one table in appadmin

Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/www-data/web2py/applications/putevki/views/appadmin.html", line 196, in <module>
    <p>
  File "/home/www-data/web2py/gluon/globals.py", line 434, in write
    self.body.write(to_native(xmlescape(data)))
  File "/home/www-data/web2py/gluon/html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "/home/www-data/web2py/gluon/languages.py", line 431, in xml
    return str(self) if self.M else local_html_escape(str(self), quote=False)
  File "/home/www-data/web2py/gluon/languages.py", line 391, in __str__
    self.T.translate(self.m, self.s))
  File "/home/www-data/web2py/gluon/languages.py", line 1009, in translate
    message = self.params_substitution(message, symbols)
  File "/home/www-data/web2py/gluon/languages.py", line 987, in params_substitution
    message = regex_plural.sub(sub_plural, message)
  File "/home/www-data/web2py/gluon/languages.py", line 980, in sub_plural
    part = regex_plural_tuple.sub(sub_tuple, s)
TypeError: sequence item 0: expected str instance, bytes found

**Comment by postcoder** [comment]
db.define_table('adresses',
                Field('id', 'integer'),
                Field('ls', 'text'),
                Field('fio', 'text'),
                Field('home_adres', 'text'),
                Field('tarif', 'text'),
                Field('status', 'text'),
                ),

db.define_table('putevka_setting',
               Field('count_day','integer'),
               Field('min_vyezd_per_day','integer'),
               Field('max_vyezd_per_day','integer'),
               Field('ofice_adress','string'),
               ),
db.define_table('putevka_archive',
#               Field('put_mounth','string'),
               Field('put_start_day','date'),
               Field('put_cur_day','date'),
               Field('put_adress','string'),
               ),

Whith all admin tables 
db.auth_user, db.auth_group & etc.

**Comment by postcoder** [comment]
I'm find where from this string.
this string is from /web2py/applications/application_name/languages/plural-ru.py

![2018-09-26 21-31-41](https://user-images.githubusercontent.com/2355645/46101332-52bac700-c1d4-11e8-9981-110a77ffc5a6.png)

first string.

**Comment by leonelcamara** [comment]
@postcoder please test
https://github.com/web2py/web2py/pull/2025

**Comment by postcoder** [comment]
traceback

Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/www-data/web2py/applications/putevki/views/appadmin.html", line 196, in <module>
    <p>
  File "/home/www-data/web2py/gluon/globals.py", line 434, in write
    self.body.write(to_native(xmlescape(data)))
  File "/home/www-data/web2py/gluon/html.py", line 125, in xmlescape
    return to_bytes(data.xml())
  File "/home/www-data/web2py/gluon/languages.py", line 431, in xml
  File "/home/www-data/web2py/gluon/languages.py", line 391, in __str__
  File "/home/www-data/web2py/gluon/languages.py", line 1009, in translate
    data = to_native(read_locked(filename))
  File "/home/www-data/web2py/gluon/languages.py", line 987, in params_substitution
    Must be run by the admin app
  File "/home/www-data/web2py/gluon/languages.py", line 980, in sub_plural
    message = self.params_substitution(message, symbols)
TypeError: sequence item 0: expected str instance, bytes found

**Comment by leonelcamara** [comment]
@postcoder was that after applying the fixes in my pull request and restarting web2py?  
  
Can you give me an example of a T call that causes the problem? I managed to reproduce your issue with:

     T('%d %%{!test[0]} %d %%{!lala[1]}', (0, 0))

And this fixed it.
