### ISSUE TITLE
FOREIGN KEY constraint failed in Web2py

### ISSUE THREAD

**Issue by Alzemand** [web2py/web2py#2029]
**FOREIGN KEY constraint failed in Web2py**

note: My English is not good, but I'll try to express myself

I created two tables in db.py:

```
Empresa = db.define_table('empresa',
    Field('cnpj', 'string', label='CNPJ'),
    Field('razao', 'string', label='Nome'),
    Field('nome', 'string', label='Nome'),
    Field('email', 'string', label="E-Mail"),
    Field('telefone', 'string', label="Telefone"),
    Field('endereco', 'text' ,label='Endereço'),
    Field('termo', 'upload', label='Termo de convênio'),
    auth.signature,
    format = "%(nome)s",
    primarykey=['cnpj']
    )

Estagio = db.define_table('estagio',
    Field('empresa', 'reference empresa', label="Empresa", ondelete='SET NULL'),
    Field('supervisor', 'string', label="Supervisor"),
    Field('data_inicio', 'date', label="Data início"),
    Field('data_fim', 'date', format=('%d-%m-%Y'), label="Data início"),
    Field('observacao', 'text', label="Observação"),
    Field('situacao', 'string', label="Situação"),
    auth.signature
)
```

This is my default.py:

```
def estagio_cadastro():
    form = SQLFORM(Estagio)
    if form.process().accepted:
        db.estagio.insert(**form.vars)
        session.flash = 'Estagio cadastrado'
        redirect(URL('estagio_cadastro'))
    elif form.errors:
        response.flash = 'Corrija os erros encontrados no formulário'
    else:
        if not response.flash:
            response.flash = 'Preencha o formulário'
    return dict(form=form)
```
I'm having trouble creating a foreign key of type string. I create the reference in db.py but for some reason, being the MySQL database the value is not saved, when I insert given type string (eg "12345") it works normally, but if I inserted ('05432') the web2py saves as ('5432') in the database, causing the error:

**<class '_mysql_exceptions.IntegrityError'> (1452, 'Cannot add or update a child row: a foreign key constraint fails (`sigedo`.`estagio`, CONSTRAINT `FK_estagio_empresa__constraint` FOREIGN KEY (`empresa`) REFERENCES `empresa` (`cnpj`) ON DELETE SET NULL)')**

```
Traceback (most recent call last):
  File "C:\web2py\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "C:/web2py/applications/sigedo/controllers/default.py", line 340, in <module>
  File "C:\web2py\gluon\globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "C:/web2py/applications/sigedo/controllers/default.py", line 278, in estagio_cadastro
    if form.process().accepted:
  File "C:\web2py\gluon\html.py", line 2302, in process
    self.validate(**kwargs)
  File "C:\web2py\gluon\html.py", line 2240, in validate
    if self.accepts(**kwargs):
  File "C:\web2py\gluon\sqlhtml.py", line 1973, in accepts
    self.vars.id = self.table.insert(**fields)
  File "C:\web2py\gluon\packages\dal\pydal\objects.py", line 766, in insert
    ret = self._db._adapter.insert(self, row.op_values())
  File "C:\web2py\gluon\packages\dal\pydal\adapters\base.py", line 487, in insert
    raise e
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`sigedo`.`estagio`, CONSTRAINT `FK_estagio_empresa__constraint` FOREIGN KEY (`empresa`) REFERENCES `empresa` (`cnpj`) ON DELETE SET NULL)')
```

Could you confirm in the bug?

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Firefox 62.0.2 (64-bit)
 - web2py™ | Version 2.17.1-stable+timestamp.2018.08.06.01.02.56
 - Python 2.7.9: C:\web2py\web2py.exe (prefix: )
 - MYSQL 8

**Additional context**

**Comment by Alzemand** [comment]
I, I believe the problem is in PYDAL, which is removing the zero from the primary key ('012345')

![image](https://user-images.githubusercontent.com/10548468/46366327-23cba780-c651-11e8-8915-3d9344e68094.png)


`>>> value = '012345' `
`>>> value = str(long(value)) `
`>>> print (value)`
`>>> '12345'`

Causing foreign key error:

<class '_mysql_exceptions.IntegrityError'> (1452, 'Cannot add or update a child row: a foreign key constraint fails (sigedo.estagio, CONSTRAINT FK_estagio_empresa__constraint FOREIGN KEY (empresa) REFERENCES empresa (cnpj) ON DELETE SET NULL)')

**Comment by WattsMatthew** [comment]
Hi Alzemand, had a similar problem. Read this in case it is any help to you.

[https://stackoverflow.com/questions/50565270/foreign-key-constraint-failed-in-web2py](url)

**Comment by Alzemand** [comment]
> 
> 
> Hi Alzemand, had a similar problem. Read this in case it is any help to you.
> 
> [https://stackoverflow.com/questions/50565270/foreign-key-constraint-failed-in-web2py](url)

Not the same problem
