### ISSUE TITLE
RedisSession + redis-py >= 3.0.0 throws DataError

### ISSUE THREAD

**Issue by RailwayMan** [web2py/web2py#2064]
Using RedisSession with redis-py >= 3.0.0 throws error like:
```
Traceback (most recent call last):
  File "/opt/web2py/gluon/main.py", line 461, in wsgibase
    session._try_store_in_db(request, response)
  File "/opt/web2py/gluon/globals.py", line 1239, in _try_store_in_db
    record_id = table.insert(**dd)
  File "/opt/web2py/gluon/contrib/redis_session.py", line 150, in insert
    pipe.execute()
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 3443, in execute
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 3309, in _execute_transaction
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 683, in pack_commands
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 659, in pack_command
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 113, in encode
DataError: Invalid input of type: 'bool'. Convert to a byte, string or number first.
```
As far as checked on [redis-py github](https://github.com/andymccurdy/redis-py/tree/3.0.0#encoding-of-user-input) since version 3.0.0 there is value type check, so 'locked' boolean attribute in RedisSession need to be casted to int.

I was trying to prepare fix but web2py is pretty new for me so I don't want to make more bugs :)

Envirement
```
web2py	Version 2.17.2-stable+timestamp.2018.10.06.11.34.06
Python 2.7.15
```

**Comment by leonelcamara** [comment]
Probably we could just use 0 and 1 instead of True and False.

**Comment by leonelcamara** [comment]
@mdipierro this can be closed as it is already fixed.
