### ISSUE TITLE
fixed broken connection in scheduler

### ISSUE THREAD

**Issue by RekGRpth** [web2py/web2py#2066]
This fix https://github.com/web2py/web2py/commit/33c6dd965655fdb2468ff2c2b8efaf1bc9bc3014 resolves the problem and not the cause. 

To reproduce, I propose to consider the following script.

```python
from gluon import DAL
from multiprocessing import Process
from psycopg2 import connect
from threading import Thread
from time import sleep
import logging
import signal
import sys

uri = 'postgres3://postgres:postgres@postgres:5432/postgres'

class DAL1():
    def __init__(self, uri):
        uri = uri.replace('postgres3', 'postgres')
        self.cursor = connect(uri).cursor()

    def executesql(self, sql):
        self.cursor.execute(sql)
        return self.cursor.fetchall()

def executor():
    db = DAL(uri)
    logging.error('executor: %s' % db.executesql('''select now()''')[0][0])

class MetaScheduler(Thread):
    def __init__(self):
        Thread.__init__(self)
        self.have_heartbeat = True

    def local_async(self):
        self.process = Process(target=executor)
        self.process.start()

    def run(self):
        counter = 0
        while self.have_heartbeat:
            self.send_heartbeat(counter)
            counter += 1
            sleep(1)

    def start_heartbeats(self):
        self.start()

    def die(self):
        self.have_heartbeat = False
        self.terminate_process()

    def terminate_process(self):
        try: self.process.terminate()
        except: pass

class Scheduler(MetaScheduler):
    def __init__(self):
        MetaScheduler.__init__(self)
        self.db = DAL(uri)
        self.db_thread = None

    def loop(self):
        signal.signal(signal.SIGTERM, lambda signum, stack_frame: sys.exit(1))
        try:
            self.start_heartbeats()
            while self.have_heartbeat:
                logging.error('loop: %s' % self.db.executesql('''select now()''')[0][0])
                self.local_async()
                sleep(1)
        except (KeyboardInterrupt, SystemExit):
            self.die()

    def send_heartbeat(self, counter):
        if not self.db_thread: self.db_thread = DAL(uri)
        try: logging.error('send_heartbeat: %s' % self.db_thread.executesql('''select now()''')[0][0])
        except:
            self.die()
            raise

def main(): Scheduler().loop()

if __name__ == '__main__': main()
```

If you run it, you get

```python
python test.py 
ERROR:root:loop: 2018-12-14 08:48:12.880449+05:00
ERROR:root:send_heartbeat: 2018-12-14 08:48:12.885317+05:00
ERROR:root:executor: 2018-12-14 08:48:12.890597+05:00
ERROR:root:loop: 2018-12-14 08:48:12.880449+05:00
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "test.py", line 37, in run
    self.send_heartbeat(counter)
  File "test.py", line 71, in send_heartbeat
    try: logging.error('send_heartbeat: %s' % self.db_thread.executesql('''select now()''')[0][0])
  File "/data/app/gluon/packages/dal/pydal/base.py", line 772, in executesql
    adapter.execute(query)
  File "/data/app/gluon/packages/dal/pydal/adapters/__init__.py", line 67, in wrap
    return f(*args, **kwargs)
  File "/data/app/gluon/packages/dal/pydal/adapters/base.py", line 413, in execute
    rv = self.cursor.execute(command, *args[1:], **kwargs)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

But if you replace DAL1 with DAL, then everything is fine!

**Comment by RekGRpth** [comment]
This bug appears only in python 3, in python 2 everything is ok
