### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by sugizo** [web2py/web2py#2108]
**Describe the bug**
Traceback (most recent call last):
  File "/Users/sugizo/project/python/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/Users/sugizo/project/python/web2py/applications/test/models/db_schema_0_auth.py", line 9, in <module>
    custom_auth_table = db[auth.settings.table_user_name]
  File "/Users/sugizo/project/python/web2py/gluon/packages/dal/pydal/base.py", line 666, in __getitem__
    return self.__getattr__(str(key))
  File "/Users/sugizo/project/python/web2py/gluon/packages/dal/pydal/base.py", line 672, in __getattr__
    return self.lazy_define_table(tablename, *fields, **kwargs)
  File "/Users/sugizo/project/python/web2py/gluon/packages/dal/pydal/base.py", line 624, in lazy_define_table
    polymodel=polymodel)
  File "/Users/sugizo/project/python/web2py/gluon/packages/dal/pydal/adapters/base.py", line 798, in create_table
    return self.migrator.create_table(*args, **kwargs)
  File "/Users/sugizo/project/python/web2py/gluon/packages/dal/pydal/migrator.py", line 279, in create_table
    query), table)
  File "/Users/sugizo/project/python/web2py/gluon/packages/dal/pydal/migrator.py", line 488, in log
    logfile.write(to_bytes(message))
  File "/Users/sugizo/project/python/web2py/gluon/packages/dal/pydal/helpers/classes.py", line 544, in write
    self.data += data
TypeError: can only concatenate str (not "bytes") to str

**To Reproduce**
models/db.py
adapter_args = dict(migrator = InDBMigrator)

**Expected behavior**
no error occured

**Desktop (please complete the following information):**
 - OS: Darwin
 - Browser Chrome
 - Version 72
 - Python 3.7.2

**Additional context**
ref:
https://groups.google.com/forum/#!topic/web2py/86CnfmYcY5w

**Comment by ybenitezf** [comment]
same here

**Comment by ybenitezf** [comment]
This solved for me:

```diff
diff --git a/gluon/packages/dal/pydal/helpers/classes.py b/gluon/packages/dal/pydal/helpers/classes.py
index edb785a..6c34471 100644
--- a/gluon/packages/dal/pydal/helpers/classes.py
+++ b/gluon/packages/dal/pydal/helpers/classes.py
@@ -541,7 +541,10 @@ class DatabaseStoredFile:
         return data
 
     def write(self, data):
-        self.data += data
+        try:
+            self.data += data.decode()
+        except (UnicodeDecodeError, AttributeError):
+            self.data += data
 
     def close_connection(self):
         if self.db is not None:
```

Using web2py `2.20.4-stable+timestamp.2020.05.03.05.18.50` and python 3.8

**Comment by ybenitezf** [comment]
The problem seens to come from `gluon/packages/dal/pydal/helpers/classes.py`
