### ISSUE TITLE
Issues on Redhat 7 / Python  2.7.13

### ISSUE THREAD

**Issue by bens4linux** [web2py/web2py#2109]
**Describe the bug**
Errors on any and all connections.
"Internal Server Error"

**To Reproduce**
Use Redhat 7 and Python 2.7.13
 
**Expected behavior**
Should Work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Redhat 7.2
 - Browser Firefox

**Additional context**
Log Errors:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Server Log:

[Mon Feb 25 07:11:02.171430 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65464] mod_wsgi (pid=48880): Exception occurred processing WSGI script '/data/web2py/web2py/wsgihandler.py'.
[Mon Feb 25 07:11:02.171483 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65464] Traceback (most recent call last):
[Mon Feb 25 07:11:02.171552 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65464]   File "/data/web2py/web2py/wsgihandler.py", line 29, in <module>
[Mon Feb 25 07:11:02.171631 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65464]     import gluon.main
[Mon Feb 25 07:11:02.171668 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65464]   File "/data/web2py/web2py/gluon/__init__.py", line 47, in <module>
[Mon Feb 25 07:11:02.171716 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65464]     from .globals import current
[Mon Feb 25 07:11:02.171748 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65464]   File "/data/web2py/web2py/gluon/globals.py", line 16, in <module>
[Mon Feb 25 07:11:02.171831 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65464]     from gluon._compat import pickle, StringIO, copyreg, Cookie, urlparse, PY2, iteritems, to_unicode, to_native, \\
[Mon Feb 25 07:11:02.171890 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65464] ImportError: cannot import name Cookie
[Mon Feb 25 07:11:20.182840 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65470] mod_wsgi (pid=48880): Target WSGI script '/data/web2py/web2py/wsgihandler.py' cannot be loaded as Python module.
[Mon Feb 25 07:11:20.182952 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65470] mod_wsgi (pid=48880): Exception occurred processing WSGI script '/data/web2py/web2py/wsgihandler.py'.
[Mon Feb 25 07:11:20.182998 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65470] Traceback (most recent call last):
[Mon Feb 25 07:11:20.183039 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65470]   File "/data/web2py/web2py/wsgihandler.py", line 29, in <module>
[Mon Feb 25 07:11:20.183113 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65470]     import gluon.main
[Mon Feb 25 07:11:20.183151 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65470]   File "/data/web2py/web2py/gluon/__init__.py", line 47, in <module>
[Mon Feb 25 07:11:20.183197 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65470]     from .globals import current
[Mon Feb 25 07:11:20.183229 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65470]   File "/data/web2py/web2py/gluon/globals.py", line 16, in <module>
[Mon Feb 25 07:11:20.183398 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65470]     from gluon._compat import pickle, StringIO, copyreg, Cookie, urlparse, PY2, iteritems, to_unicode, to_native, \\
[Mon Feb 25 07:11:20.183481 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:65470] ImportError: cannot import name Cookie
[Mon Feb 25 07:13:25.948959 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:49224] mod_wsgi (pid=48880): Target WSGI script '/data/web2py/web2py/wsgihandler.py' cannot be loaded as Python module.
[Mon Feb 25 07:13:25.949144 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:49224] mod_wsgi (pid=48880): Exception occurred processing WSGI script '/data/web2py/web2py/wsgihandler.py'.
[Mon Feb 25 07:13:25.949311 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:49224] Traceback (most recent call last):
[Mon Feb 25 07:13:25.949422 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:49224]   File "/data/web2py/web2py/wsgihandler.py", line 29, in <module>
[Mon Feb 25 07:13:25.949594 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:49224]     import gluon.main
[Mon Feb 25 07:13:25.949688 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:49224]   File "/data/web2py/web2py/gluon/__init__.py", line 47, in <module>
[Mon Feb 25 07:13:25.949804 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:49224]     from .globals import current
[Mon Feb 25 07:13:25.949894 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:49224]   File "/data/web2py/web2py/gluon/globals.py", line 16, in <module>
[Mon Feb 25 07:13:25.950056 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:49224]     from gluon._compat import pickle, StringIO, copyreg, Cookie, urlparse, PY2, iteritems, to_unicode, to_native, \\
[Mon Feb 25 07:13:25.950185 2019] [wsgi:error] [pid 48880] [remote 10.13.69.144:49224] ImportError: cannot import name Cookie

**Comment by djordjen** [comment]
Same issue on Windows 10 after the latest update (Python v2.7.13):

`D:\web2py>python --version
Python 2.7.13

D:\web2py>python web2py.py
Traceback (most recent call last):
  File "web2py.py", line 21, in <module>
    import gluon.widget
  File "D:\web2py\gluon\__init__.py", line 47, in <module>
    from .globals import current
  File "D:\web2py\gluon\globals.py", line 16, in <module>
    from gluon._compat import pickle, StringIO, copyreg, Cookie, urlparse, PY2, iteritems, to_unicode, to_native, \
ImportError: cannot import name Cookie`

Tried downloading and running a clear source install from web2py.com - same outcome.

**Comment by JusticeN** [comment]
after an upgrade i can not start the web2py server anymore.

**Comment by soyharso** [comment]
Same error here
