### ISSUE TITLE
Can you consider changing the included web server? The official Rocket web server is not updated since 2011-05-01.

### ISSUE THREAD

**Issue by jcrmatos** [web2py/web2py#2113]
Can you consider changing the included web server?
The official Rocket web server is not updated since 2011-05-01.
Here
`https://wiki.python.org/moin/WebServers`
there is a list of several other Python based web servers.

**Comment by leonelcamara** [comment]
Why bother? I mean, it works pretty well for development and no one uses it in production.

**Comment by jcrmatos** [comment]
In my case it keeps showing errors like this

web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2019
Version 2.18.2-stable+timestamp.2019.02.26.06.11.06
Database drivers available: sqlite3, pyodbc, imaplib, pymysql

please visit:
        http://192.168.255.1:8000/
use "taskkill /f /pid 6288" to shutdown the web2py server


ERROR:Rocket.Errors.Thread-3:Traceback (most recent call last):

  File "C:\web2py\gluon\rocket.py", line 1288, in run
    self.run_app(conn)

  File "C:\web2py\gluon\rocket.py", line 1781, in run_app
    self.environ = environ = self.build_environ(sock_file, conn)

  File "C:\web2py\gluon\rocket.py", line 1601, in build_environ
    request = self.read_request_line(sock_file)

  File "C:\web2py\gluon\rocket.py", line 1339, in read_request_line
    d = sock_file.readline()

  File "C:\Users\JMatos\OneDrive\Python\winpython371-32\python-3.7.1\lib\socket.
py", line 589, in readinto
    return self._sock.recv_into(b)

ConnectionResetError: [WinError 10054] Uma ligação existente foi forçada a fecha
r pelo anfitrião remoto

ERROR:Rocket.Errors.Thread-3:Tried to send "500 Server Error" to client but rece
ived socket error
ERROR:Rocket.Errors.Thread-7:Traceback (most recent call last):

  File "C:\web2py\gluon\rocket.py", line 1288, in run
    self.run_app(conn)

  File "C:\web2py\gluon\rocket.py", line 1781, in run_app
    self.environ = environ = self.build_environ(sock_file, conn)

  File "C:\web2py\gluon\rocket.py", line 1601, in build_environ
    request = self.read_request_line(sock_file)

  File "C:\web2py\gluon\rocket.py", line 1339, in read_request_line
    d = sock_file.readline()

  File "C:\Users\JMatos\OneDrive\Python\winpython371-32\python-3.7.1\lib\socket.
py", line 589, in readinto
    return self._sock.recv_into(b)

ConnectionResetError: [WinError 10054] Uma ligação existente foi forçada a fecha
r pelo anfitrião remoto

ERROR:Rocket.Errors.Thread-7:Tried to send "500 Server Error" to client but rece
ived socket error
ERROR:Rocket.Errors.Thread-3:Traceback (most recent call last):

  File "C:\web2py\gluon\rocket.py", line 1288, in run
    self.run_app(conn)

  File "C:\web2py\gluon\rocket.py", line 1781, in run_app
    self.environ = environ = self.build_environ(sock_file, conn)

  File "C:\web2py\gluon\rocket.py", line 1601, in build_environ
    request = self.read_request_line(sock_file)

  File "C:\web2py\gluon\rocket.py", line 1339, in read_request_line
    d = sock_file.readline()

  File "C:\Users\JMatos\OneDrive\Python\winpython371-32\python-3.7.1\lib\socket.
py", line 589, in readinto
    return self._sock.recv_into(b)

ConnectionResetError: [WinError 10054] Uma ligação existente foi forçada a fecha
r pelo anfitrião remoto

ERROR:Rocket.Errors.Thread-3:Tried to send "500 Server Error" to client but rece
ived socket error

**Comment by jcrmatos** [comment]
You were right. It was the firewall. Thanks for the tip.
