### ISSUE TITLE
Regular errors in Rocket

### ISSUE THREAD

**Issue by jcrmatos** [web2py/web2py#2116]
Hello,

On my system

Windows 7 Pro x64 with SP1+all updates
Python 3.7.1 x86
web2py 2.8.12 (which includes rocket 1.2.6? - the last official version is 1.2.4 from 2011)
Firefox 65.0.2 x64

the rocket web server keeps showing these error messages

```
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2019
Version 2.18.2-stable+timestamp.2019.02.26.06.11.06
Database drivers available: sqlite3, pyodbc, imaplib, pymysql

please visit:
http://192.168.255.1:8000/
use "taskkill /f /pid 6288" to shutdown the web2py server

ERROR:Rocket.Errors.Thread-3:Traceback (most recent call last):

File "C:\web2py\gluon\rocket.py", line 1288, in run
self.run_app(conn)

File "C:\web2py\gluon\rocket.py", line 1781, in run_app
self.environ = environ = self.build_environ(sock_file, conn)

File "C:\web2py\gluon\rocket.py", line 1601, in build_environ
request = self.read_request_line(sock_file)

File "C:\web2py\gluon\rocket.py", line 1339, in read_request_line
d = sock_file.readline()

File "C:\Users\JMatos\OneDrive\Python\winpython371-32\python-3.7.1\lib\socket.
py", line 589, in readinto
return self._sock.recv_into(b)

ConnectionResetError: [WinError 10054] Uma ligação existente foi forçada a fecha
r pelo anfitrião remoto

ERROR:Rocket.Errors.Thread-3:Tried to send "500 Server Error" to client but rece
ived socket error
ERROR:Rocket.Errors.Thread-7:Traceback (most recent call last):

File "C:\web2py\gluon\rocket.py", line 1288, in run
self.run_app(conn)

File "C:\web2py\gluon\rocket.py", line 1781, in run_app
self.environ = environ = self.build_environ(sock_file, conn)

File "C:\web2py\gluon\rocket.py", line 1601, in build_environ
request = self.read_request_line(sock_file)

File "C:\web2py\gluon\rocket.py", line 1339, in read_request_line
d = sock_file.readline()

File "C:\Users\JMatos\OneDrive\Python\winpython371-32\python-3.7.1\lib\socket.
py", line 589, in readinto
return self._sock.recv_into(b)

ConnectionResetError: [WinError 10054] Uma ligação existente foi forçada a fecha
r pelo anfitrião remoto

ERROR:Rocket.Errors.Thread-7:Tried to send "500 Server Error" to client but rece
ived socket error
ERROR:Rocket.Errors.Thread-3:Traceback (most recent call last):

File "C:\web2py\gluon\rocket.py", line 1288, in run
self.run_app(conn)

File "C:\web2py\gluon\rocket.py", line 1781, in run_app
self.environ = environ = self.build_environ(sock_file, conn)

File "C:\web2py\gluon\rocket.py", line 1601, in build_environ
request = self.read_request_line(sock_file)

File "C:\web2py\gluon\rocket.py", line 1339, in read_request_line
d = sock_file.readline()

File "C:\Users\JMatos\OneDrive\Python\winpython371-32\python-3.7.1\lib\socket.
py", line 589, in readinto
return self._sock.recv_into(b)

ConnectionResetError: [WinError 10054] Uma ligação existente foi forçada a fecha
r pelo anfitrião remoto

ERROR:Rocket.Errors.Thread-3:Tried to send "500 Server Error" to client but rece
ived socket error
```

Thanks in advance for any help,

JM

**Comment by leonelcamara** [comment]
Is this running locally? If it is why are you using 192.168.255.1 instead of 127.0.0.1, could it be your firewall blocking rocket?

**Comment by jcrmatos** [comment]
Yes it is running locally. I'm using the net IP instead of localhost because I want to test everything like it will work on the client.
That is the strange part. Nothing gets blocked. The errors keep showing up, but the app and web2py keep running without any problem. 
I even checked the httpserver.log and nothing shows up.

**Comment by leonelcamara** [comment]
It's weird because I can't reproduce these problems, could it be because of winpython? Have you tried with the regular python you get from python.org.

**Comment by jcrmatos** [comment]
You were right, it was the firewall. Thanks for the tip.
