### ISSUE TITLE
AttributeError: strip

### ISSUE THREAD

**Issue by rif** [web2py/web2py#2124]
**Describe the bug**
After login (I am only using captcha) I am redirected to https://rjas.ro/user/login?_next=/# and an error ticket is generated

**To Reproduce**
1. enter user and pass
2. complete captcha
3. hit login

**Expected behavior**
Login used to work correctly in previos version

**Screenshots**
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/www-data/web2py/applications/rjas/controllers/default.py", line 353, in <module>
  File "/home/www-data/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/home/www-data/web2py/applications/rjas/controllers/default.py", line 297, in user
    return dict(form=auth())
  File "/home/www-data/web2py/gluon/tools.py", line 1801, in __call__
    return getattr(self, args[0])()
  File "/home/www-data/web2py/gluon/tools.py", line 2577, in login
    hideerror=settings.hideerror):
  File "/home/www-data/web2py/gluon/sqlhtml.py", line 1758, in accepts
    **kwargs
  File "/home/www-data/web2py/gluon/html.py", line 2148, in accepts
    status = self._traverse(status, hideerror)
  File "/home/www-data/web2py/gluon/html.py", line 909, in _traverse
    newstatus = c._traverse(status, hideerror) and newstatus
  File "/home/www-data/web2py/gluon/html.py", line 909, in _traverse
    newstatus = c._traverse(status, hideerror) and newstatus
  File "/home/www-data/web2py/gluon/html.py", line 909, in _traverse
    newstatus = c._traverse(status, hideerror) and newstatus
  File "/home/www-data/web2py/gluon/html.py", line 909, in _traverse
    newstatus = c._traverse(status, hideerror) and newstatus
  File "/home/www-data/web2py/gluon/html.py", line 916, in _traverse
    newstatus = self._validate()
  File "/home/www-data/web2py/gluon/tools.py", line 912, in _validate
    httpresp = urlopen(request)
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 185, in open
    fullurl = unwrap(toBytes(fullurl))
  File "/usr/lib/python2.7/urllib.py", line 1071, in unwrap
    url = url.strip()
  File "/usr/lib/python2.7/urllib2.py", line 254, in __getattr__
    raise AttributeError, attr
AttributeError: strip
**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser firefox 
 - Version 65.0.2

**Additional context**
Only happens after I upgraded to 2.18.2

**Comment by rif** [comment]
Fixed with the latest version
