### ISSUE TITLE
"Ran out of input" on cache.disk file

### ISSUE THREAD

**Issue by jicho** [web2py/web2py#2175]
**Describe the bug**
For some reason, we can't figure out why, we end up with a cache file that contains no data. So we have an empty file. When this happens Web2Py breaks with the error:

```
<class 'EOFError'> Ran out of input

Traceback (most recent call last):
  File "/data-store/app/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/data-store/app/applications/Tetra/views/default/index.html", line 82, in <module>
  File "/data-store/app/applications/Tetra/modules/notification_helpers.py", line 22, in get_notifications
    time_expire=3600
  File "/data-store/app/gluon/cache.py", line 444, in __call__
    item = self.storage.get(key)
  File "/data-store/app/gluon/cache.py", line 401, in get
    return self[key]
  File "/data-store/app/gluon/cache.py", line 350, in __getitem__
    value = pickle.load(val_file)
EOFError: Ran out of input
```

The cache file is created like this:
```
class NotificationHelpers(object):
    api_key = 'global_notifications'

    @staticmethod
    def notifications_query():
        return current.db(
            (current.db.notifications.visible_till == None) |
            (current.db.notifications.visible_till >= current.request.now)
        ).select(
            orderby=(~current.db.notifications.is_important | ~current.db.notifications.created)
        )

    @classmethod
    def get_notifications(cls):
        result = []

        try:
            result = current.cache.disk(
                cls.api_key,
                lambda: cls.notifications_query(),
                time_expire=3600
            )
        except Exception as e:
            current.logger.error("Can't read cache file ({0}): {1}", cls.api_key, e)
            current.cache.disk(cls.api_key, None)

        return result
```

The exception was added to catch the error and the idea of "current.cache.disk(cls.api_key, None)" was to remove the file, but this also ends with the "EOFError: Ran out of input" error.

Removing the file was only to see if this deletes the file and stops the error.

The original code was like this:
```
class NotificationHelpers(object):
    api_key = 'global_notifications'

    @staticmethod
    def notifications_query():
        return current.db(
            (current.db.notifications.visible_till == None) |
            (current.db.notifications.visible_till >= current.request.now)
        ).select(
            orderby=(~current.db.notifications.is_important | ~current.db.notifications.created)
        )

    @classmethod
    def get_notifications(cls):
        result = current.cache.disk(
            cls.api_key,
            lambda: cls.notifications_query(),
            time_expire=3600
        )

        return result
```

**To Reproduce**
1. Create a cache file that is stored on disk
2. To mimic the situation... Empty the file on disk, but leave the file
3. Go to your website and press F5

**Expected behavior**
I would expect that the caching logic does not store empty files since it can't handle them. 

**Additional context**
I know it would help if we would know how we end up with a file of 0Kb, but... that's a strange one, we really have no clue :( It also happens randomly on our production server.

**Comment by DavidAustin** [comment]
I had this happen when the disk became full.  One of the cache files was then zero length, causing all sorts of strife.

IMHO, the cache module should treat an empty or unreadable cache file as missing, rather than passing up the EOFError exception.
