### ISSUE TITLE
RuntimeError with extract_oracle_models.py

### ISSUE THREAD

**Issue by ljudva** [web2py/web2py#2193]
Hi guys, 

just reviewing the utils and the extract_oracle_models.py is not happy:

```
.
.
db.define_table('
.
.
.
    Field('LAST_TRX_DATE', type='datetime', comment='Alternative types: date'),
Traceback (most recent call last):
  File "extract_oracle_models.py", line 312, in <module>
    define_db(cnn, db, host, port, user, passwd)
  File "extract_oracle_models.py", line 297, in define_db
    define_table(conn, table)
  File "extract_oracle_models.py", line 275, in define_table
    fdef = define_field(conn, table, field, pks)
  File "extract_oracle_models.py", line 100, in define_field
    ref = references(conn, table, field['COLUMN_NAME'])
  File "extract_oracle_models.py", line 265, in references
    str(rows1))
RuntimeError: Unsupported referential constraint: [{'ORDINAL_POSITION': 1, 'DELETE_RULE': 'NO ACTION', 'CONSTRAINT_NAME': 'CASH_LEDGER_CASH_LEDGER'}, {'ORDINAL_POSITION': 1, 'DELETE_RULE': 'NO ACTION', 'CONSTRAINT_NAME': 'LEDG_ACC_P_PARTICIPANTS'}]
```

The Oracle is:
Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, Oracle Label Security, OLAP, Data Mining
and Real Application Testing options

Please advice how to solve this.

Thanks

**Comment by ljudva** [comment]
I can confirm that this is happening with Oracle 12.1.0.2.0.

Exactly the same error. I can provide the table details privately.
