### ISSUE TITLE
Scheduler exception in ubuntu16.04+mysql5.6+Python3.6

### ISSUE THREAD

**Issue by LoveEatCandy** [web2py/web2py#2242]
Only error in linux. win10 is OK.

Traceback (most recent call last):
  File "/home/www-data/web2py2000/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "applications/sai_admin/models/menu.py", line 49, in <module>
    menus = menu_service.get_menu_config()
  File "/home/www-data/web2py2000/applications/sai_admin/modules/system_menu.py", line 94, in get_menu_config
    menus = db(query).select(orderby=db.kc_menu.order_id)
  File "/home/www-data/web2py2000/gluon/packages/dal/pydal/objects.py", line 2395, in select
    return adapter.select(self.query, fields, attributes)
  File "/home/www-data/web2py2000/gluon/packages/dal/pydal/adapters/base.py", line 763, in select
    return self._select_aux(sql, fields, attributes, colnames)
  File "/home/www-data/web2py2000/gluon/packages/dal/pydal/adapters/base.py", line 719, in _select_aux
    rows = self._select_aux_execute(sql)
  File "/home/www-data/web2py2000/gluon/packages/dal/pydal/adapters/base.py", line 713, in _select_aux_execute
    self.execute(sql)
  File "/home/www-data/web2py2000/gluon/packages/dal/pydal/adapters/__init__.py", line 63, in wrap
    if not args[0].connection:
  File "/home/www-data/web2py2000/gluon/packages/dal/pydal/connection.py", line 38, in connection
    return getattr(THREAD_LOCAL, self._connection_uname_)
AttributeError: '_thread._local' object has no attribute '_pydal_connection_139873283860576_19462'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www-data/web2py2000/gluon/shell.py", line 180, in env
    run_models_in(environment)
  File "/home/www-data/web2py2000/gluon/compileapp.py", line 563, in run_models_in
    restricted(ccode, environment, layer=model)
  File "/home/www-data/web2py2000/gluon/restricted.py", line 235, in restricted
    raise RestrictedError(layer, scode, output, environment)
gluon.restricted.RestrictedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www-data/web2py2000/gluon/scheduler.py", line 488, in executor
    extra_request={'is_scheduler': True})
  File "/home/www-data/web2py2000/gluon/shell.py", line 183, in env
    sys.exit(1)
SystemExit: 1

**Comment by LoveEatCandy** [comment]
add "db._adapter.reconnect()" can fix the bug temporarily.
