### ISSUE TITLE
Worker has an "error cleaning up" at each attempt

### ISSUE THREAD

**Issue by mikael-s** [web2py/web2py#2244]
When there are enough workers with a low heartbeat (in my application 6 workers with a 5-second heartbeat), the workers eventually tend to produce an “Error cleaning up”.
When investigating, the traceback behind this exception is:
```
ERROR:web2py.scheduler.cca9e2afbb5f#22:Error cleaning up: Traceback (most recent call last):
  File "/usr/share/vidjil/server/web2py/gluon/scheduler.py", line 1237, in send_heartbeat
    ).update(assigned_worker_name='', status=QUEUED)
  File "/usr/share/vidjil/server/web2py/gluon/packages/dal/pydal/objects.py", line 2314, in update
    ret = db._adapter.update(table, self.query, row.op_values())
  File "/usr/share/vidjil/server/web2py/gluon/packages/dal/pydal/adapters/base.py", line 524, in update
    raise e
InternalError: (1213, u'Deadlock found when trying to get lock; try restarting transaction')
```

When doing a `show engine innodb status` in mysql, the deadlock found is:
```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2019-08-22 12:01:13 0x7f5ff431b700
*** (1) TRANSACTION:
TRANSACTION 29276596, ACTIVE 1 sec starting index read
mysql tables in use 2, locked 2
LOCK WAIT 5 lock struct(s), heap size 1136, 3 row lock(s), undo log entries 1
MySQL thread id 368, OS thread handle 140050093389568, query id 128634 172.19.0.5 vidjil updating
UPDATE `scheduler_task` SET `status`='QUEUED',`assigned_worker_name`='' WHERE ((`scheduler_task`.`assigned_worker_name` IN (SELECT `scheduler_worker`.`worker_name` FROM `scheduler_worker` WHER
E (((`scheduler_worker`.`last_heartbeat` < '2019-08-22 12:00:57') AND (`scheduler_worker`.`status` = 'ACTIVE')) OR ((`scheduler_worker`.`last_heartbeat` < '2019-08-22 11:57:27') AND (`schedule
r_worker`.`status` <> 'ACTIVE'))))) AND (`scheduler_task`.`status` = 'RUNNING'))
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 62 page no 5 n bits 144 index PRIMARY of table `vidjil`.`scheduler_task` trx id 29276596 lock_mode X waiting

[…]


*** (2) TRANSACTION:
TRANSACTION 29276595, ACTIVE 1 sec starting index read
mysql tables in use 2, locked 2
722 lock struct(s), heap size 73936, 54566 row lock(s), undo log entries 1
MySQL thread id 366, OS thread handle 140050095519488, query id 128624 172.19.0.5 vidjil preparing
UPDATE `scheduler_task` SET `status`='QUEUED',`assigned_worker_name`='' WHERE ((`scheduler_task`.`assigned_worker_name` IN (SELECT `scheduler_worker`.`worker_name` FROM `scheduler_worker` WHERE (((`scheduler_worker`.`last_heartbeat` < '2019-08-22 12:00:57') AND (`scheduler_worker`.`status` = 'ACTIVE')) OR ((`scheduler_worker`.`last_heartbeat` < '2019-08-22 11:57:27') AND (`scheduler_worker`.`status` <> 'ACTIVE'))))) AND (`scheduler_task`.`status` = 'RUNNING'))
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 62 page no 5 n bits 144 index PRIMARY of table `vidjil`.`scheduler_task` trx id 29276595 lock_mode X

[…]
```

This is all the more problematic since this prevents the assignment of tasks. When the ticker has an “Error cleaning up” this raises an exception, thus those lines in `scheduler.py` are not executed and tasks are not assigned:
```python
                    if self.w_stats.status == ACTIVE:
                        self.do_assign_tasks = True
```

With this problem, which happens on several servers, we could wait hours before seeing a task assigned.

We're working with Web2py 2.17.2.

I see two workarounds:
* Lowering the number of workers or increasing the heartbeat. This doesn't feel very satisfactory.
* Moving the two lines of code shown above outside of the `try`/`except` block.

The second workaround seems more satisfactory.

What could be a real solution? Some people say that when having a deadlock we should retry the query after some delay. Is this an option? Are there other solutions?

Thanks!

**Comment by niphlod** [comment]
6 workers with 5 sec heartbeat generating concurrency issues point towards the database server not being up for the challenge. Those problems even with a low-performance backend start(ed) to arise at 10-15 workers. Try updating, I see lots of contributions made by Paolo Pastori, although I don't really see any that would lower the pressure on the worker_table db.

**Comment by mikael-s** [comment]
Thanks for your help!

I don't think the issue is coming from a low-performance server: we are running on a VM with 8 virtual CPUs and 28GB of RAM and the MySQL process is always well below 100% CPU.

> it's just erroring out on assigning tasks, not updating the worker status, which is another kind of bad-ish performances

Well that's not really on assigning task because `self.do_assign_tasks` is not set to `True` in hours, which is a consequence of the “Error cleaning up” (because of where the try/except block is placed)

**Comment by niphlod** [comment]
Contention with concurrency is more a matter of fast disk access times
rather than CPU or RAM, however if you can't do nothing about it maybe try
to switch to the redis backed scheduler

Il ven 6 set 2019, 18:49 Mikael <notifications@github.com> ha scritto:
