### ISSUE TITLE
ERROR:web2py:cannot get Tk root window, GUI disabled

### ISSUE THREAD

**Issue by cwsutherland** [web2py/web2py#2250]
Ubuntu 18.04
Web2py server won't run

python3 web2py.py 
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2019
Version 2.18.5-stable+timestamp.2019.04.07.21.13.59
Database drivers available: sqlite3, imaplib, pymysql
ERROR:web2py:cannot get Tk root window, GUI disabled
Traceback (most recent call last):
  File "/home/craig/web2py/gluon/widget.py", line 788, in start
    root = tkinter.Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
choose a password:

please visit:
	http://127.0.0.1:8000/
use "kill -SIGTERM 1478" to shutdown the web2py server

The web interface doesn't run, am I missing something fundamental not covered in the docs?

**Comment by tony1959** [comment]
Same thing for me.
Does this relate to not running it on the same device (like a raspberry with desktop and screen attached)?

**Comment by leonelcamara** [comment]
It's a matter of the command line options you're running web2py with, if you run it like this

    python web2py.py -a 'your admin password' -i 127.0.0.1 -p 8000

It will skip the TK interface.
