### ISSUE TITLE
python3 / pdf -> Internal error

### ISSUE THREAD

**Issue by macfiron** [web2py/web2py#2289]
**Describe the bug**
I used a freshly installed ubuntu 18.04 to start web2py with python3 interpreter.
Accessing the (generic) pdf view generates an internal error for the index page of the welcome app.

**To Reproduce**
1) start python3 ./web2py.py -a 'abcd1234'
browse to http://localhost:8000/welcome/default/index.pdf

**Expected behavior**
Get a pdf file of the index page.

**Screenshots**
![image](https://user-images.githubusercontent.com/5379374/75662347-35aee100-5c6f-11ea-91b6-95765721087e.png)

**Desktop (please complete the following information):**
 - OS:
  Distributor ID: Ubuntu
  Description:    Ubuntu 18.04.3 LTS
  Release:        18.04
  Codename:       bionic
 - Browser: 
  Firefox 73.0.1 (64)
 - Version: 
  web2py 2.18.5-stable+timestamp.2019.04.08.04.22.03

**Additional context**

**Comment by miversen33** [comment]
I've spent some time digging into this issue, it appears to be with how web2py handles byte code. In particular, web2py dies when trying to cast the received bytecode from the pdf, to a string (to be transmitted to the browser).

In particular, it is dying in 
/packages/dal/pydal/_compat.py
I believe it is related to line 133
`def to_native(obj, charset='utf8', errors='strict'):
        if obj is None or isinstance(obj, str):
            return obj
        return obj.decode(charset, errors)`

I dont know exactly how to deal with this, but I believe this is where it is failing.

**Comment by yaminle** [comment]
I think this error has to do with python3 fpdf is handling the pdf internally as byte-stream now. One can use the controller below (eg in the welcome app) and produce a pdf by visiting "http://localhost:8000/welcome/pdfservice/call/run/generatePDF" in a browser.

This will produce a pdf, but in the wrong encoding (i.e. utf-8) which shlould be latin1. Change the files encoding to latin1 after downloading it and it will be valid.

The change on has to make is to append the `pdf.output(dest="S").decode('latin1')` in the line where the pdf is returned. Did not find a solution so far to get the downloaded file in the correct encoding.

Just rename the txt - file to .py and use it as a controller in e.g. the welcome-app.
[pdfservice.txt](https://github.com/web2py/web2py/files/4490974/pdfservice.txt)

If, by any chance, someone knows how to set the fileencoding such that it is stored correctly - I will also appreciate that ;)

Cheers, yaminle

**Comment by macfiron** [comment]
Web2py 4TW :)

Unfortunately, I'm still stuck with this issue. I had written a PDF class in my application, that produces output according to our corporate design. The generation is based on either the internal FPDF or an externally provided FPDF module. Not being able to run this with python3 got me stuck with python2 (where for some reason this worked [presumably by accident]). Utilizing several versions of python3, even the workarounds do not work [anymore, if ever]. I took the liberty of examining the code of response and I reach the following conclusion:

**The mechanism that renders the data and returns it to the client tries to force the output of `=pdf.output(dest='S')` to be a string of some kind. The header (if the method would produce a pdf) would say Content-Type: "application/pdf" and as far as I understand PDF, it is a binary file format. Trying to coerce it to any form of [un-]encoded string is condemned to fail in the first place. Whatever comes out of pdf.output() looks like binary data and should therefore be treated as binary data.**

It is my impression, that the response class simply lacks the ability to return binary data, that was produced by a view. Clearly this example is so basic (I did not produce any additional code, see below) and if generating PDFs via integrated FPDF is meant to work, than the case below should not fail!


1) Steps to produce the error on ubuntu:20.04 (docker image used)
```
$ cat /etc/issue
Ubuntu 20.04.5 LTS \n \l

$ cat ../web2py/VERSION
Version 2.22.5-stable+timestamp.2022.06.04.18.13.51
$ python --version
Python 3.8.10

```
Then I connected to the admin interface and created a new application "printtest", switchted http://127.0.0.1/printtest/index.pdf and recieved the following error:

Traceback (most recent call last):
  File "/opt/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/opt/web2py/applications/printtest/views/generic.pdf", line 9, in <module>
    pass
  File "/opt/web2py/gluon/contrib/generics.py", line 76, in pdf_from_html
    return pyfpdf_from_html(html)
  File "/opt/web2py/gluon/contrib/generics.py", line 68, in pyfpdf_from_html
    return XML(pdf.output(dest='S'))
  File "/opt/web2py/gluon/html.py", line 644, in __init__
    text = to_native(text)
  File "/opt/web2py/gluon/packages/dal/pydal/_compat.py", line 147, in to_native
    return obj.decode(charset, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 9628: invalid start byte


2) Last but not least and for completeness sake: Using a more recent version of ubuntu:latest as docker image renders another error.
```
$ cat /etc/issue
Ubuntu 22.04.1 LTS \n \l

$ cat VERSION
Version 2.22.5-stable+timestamp.2022.06.04.18.13.51
$ python --version
Python 3.10.6

```
Traceback (most recent call last):
  File "/opt/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/opt/web2py/applications/printtest/views/generic.pdf", line 9, in <module>
    pass
  File "/opt/web2py/gluon/contrib/generics.py", line 76, in pdf_from_html
    return pyfpdf_from_html(html)
  File "/opt/web2py/gluon/contrib/generics.py", line 67, in pyfpdf_from_html
    pdf.write_html(html, image_map=image_map)
  File "/opt/web2py/gluon/contrib/fpdf/html.py", line 400, in write_html
    text = h2p.unescape(text) # To deal with HTML entities
AttributeError: 'HTML2FPDF' object has no attribute 'unescape'

I believe that there is already an issue for the unescape error, so, I do not wish to address this here.
