### ISSUE TITLE
2.19.1 GAE module object error

### ISSUE THREAD

**Issue by jparga** [web2py/web2py#2296]
**Describe the bug**
Get an error in 2.19.1 in local execution GAE, while it works fine en 2.18.5

_*Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 273, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/home/jacinto/PROGRAMACION/web2py2191/gaehandler.py", line 71, in newfun
    executed_function = fun(env, res)
  File "/home/jacinto/PROGRAMACION/web2py2191/gaehandler.py", line 96, in wsgiapp
    gluon.admin.create_missing_folders()
AttributeError: 'module' object has no attribute 'admin'
INFO     2020-03-23 19:11:03,708 module.py:865] default: "GET / HTTP/1.1" 500 -_

**Comment by jparga** [comment]
Solved with pydal  version  20200531.3
