### ISSUE TITLE
connect  mysql

### ISSUE THREAD

**Issue by Luthfunnaher** [web2py/web2py#2298]
How to connect mysql with web2py. my error is: 'password' is an invalid keyword argument for this function

**Comment by plter** [comment]
Your should provide more details.

**Comment by plter** [comment]
You shuld provide more details.

**Comment by Luthfunnaher** [comment]
1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.18.19.20.21.22.23.24.25.26.27.28. | Traceback (most recent call last):  File "C:\web2py\gluon\restricted.py", line 219, in restricted    exec(ccode, environment)  File "C:\web2py\applications\test\models\common_cid.py", line 1, in <module>    db = DAL('mysql://root:123@localhost/test',fake_migrate_all=True)  File "C:\web2py\gluon\packages\dal\pydal\base.py", line 171, in __call__    obj = super(MetaDAL, cls).__call__(*args, **kwargs)  File "C:\web2py\gluon\packages\dal\pydal\base.py", line 477, in __init__    "Failure to connect, tried %d times:\n%s" % (attempts, tb)RuntimeError: Failure to connect, tried 5 times:Traceback (most recent call last):  File "C:\web2py\gluon\packages\dal\pydal\base.py", line 457, in __init__    self._adapter = adapter(**kwargs)  File "C:\web2py\gluon\packages\dal\pydal\adapters\__init__.py", line 39, in __call__    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)  File "C:\web2py\gluon\packages\dal\pydal\adapters\base.py", line 369, in __init__    super(SQLAdapter, self).__init__(*args, **kwargs)  File "C:\web2py\gluon\packages\dal\pydal\adapters\base.py", line 53, in __init__    self.reconnect()  File "C:\web2py\gluon\packages\dal\pydal\connection.py", line 154, in reconnect    self.connection = self.connector()  File "C:\web2py\gluon\packages\dal\pydal\adapters\mysql.py", line 51, in connector    return self.driver.connect(**self.driver_args)  File "MySQLdb/__init__.py", line 81, in Connect  File "MySQLdb/connections.py", line 193, in __init__TypeError: 'password' is an invalid keyword argument for this function
-- | --

**Comment by Luthfunnaher** [comment]
i want to connect localhost . 

db = DAL('mysql://root:563@localhost/test')

**Comment by plter** [comment]
In web2py, you can just modify the file `appconfig.ini` which is in your application's 'private' directory ( for example: /path/to/web2py/applications/yourapp/private/appconfig.ini ) to connect a database ,  and then you can use the global var named db in everywhere of your applicaton context.

**Comment by DonaldMcC** [comment]
Which version are you getting this on?  This was a bug in 2.18.5 but is fixed in 2.19.1

Donald
