### ISSUE TITLE
Error when connecting sessions to db

### ISSUE THREAD

**Issue by javitgarcia** [web2py/web2py#2301]
Version: Version 2.19.1-stable+timestamp.2020.03.21.21.49.28
OS: MS-Windows-10
Python: Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32

App: welcome
File: models/db.py
# db.uri is 'sqlite://storage.sqlite'
db = DAL(configuration.get('db.uri'),
         pool_size=configuration.get('db.pool_size'),
         migrate_enabled=configuration.get('db.migrate'),
         check_reserved=['all'])
session.connect(request, response, db=db)

Error: First access is ok and session is stored in DB, but when you try to reload the page (F5)

1.2.3.4.5.6.7.8.9.10.11.12.13.14.15.16.17.18.19.20.21.22.23.24.25.26.27. | Traceback (most recent call last):  File "C:\Users\Javi\code\python\web2py_src\gluon\restricted.py", line 219, in restricted    exec(ccode, environment)  File "C:\Users\Javi\code\python\web2py_src\applications\welcome\models\db.py", line 37, in <module>    session.connect(request, response, db=db)  File "C:\Users\Javi\code\python\web2py_src\gluon\globals.py", line 971, in connect    row = table(record_id, unique_key=unique_key)  File "C:\Users\Javi\code\python\web2py_src\gluon\packages\dal\pydal\objects.py", line 703, in __call__    orderby_on_limitby=False,  File "C:\Users\Javi\code\python\web2py_src\gluon\packages\dal\pydal\objects.py", line 2634, in select    return adapter.select(self.query, fields, attributes)  File "C:\Users\Javi\code\python\web2py_src\gluon\packages\dal\pydal\adapters\sqlite.py", line 85, in select    return super(SQLite, self).select(query, fields, attributes)  File "C:\Users\Javi\code\python\web2py_src\gluon\packages\dal\pydal\adapters\base.py", line 878, in select    return self._select_aux(sql, fields, attributes, colnames)  File "C:\Users\Javi\code\python\web2py_src\gluon\packages\dal\pydal\adapters\base.py", line 835, in _select_aux    rows = self._select_aux_execute(sql)  File "C:\Users\Javi\code\python\web2py_src\gluon\packages\dal\pydal\adapters\base.py", line 829, in _select_aux_execute    self.execute(sql)  File "C:\Users\Javi\code\python\web2py_src\gluon\packages\dal\pydal\adapters\__init__.py", line 69, in wrap    return f(*args, **kwargs)  File "C:\Users\Javi\code\python\web2py_src\gluon\packages\dal\pydal\adapters\base.py", line 461, in execute    rv = self.cursor.execute(command, *args[1:], **kwargs)  File "C:\python\python376\lib\sqlite3\dbapi2.py", line 67, in convert_timestamp    datepart, timepart = val.split(b" ")ValueError: not enough values to unpack (expected 2, got 1)
-- | --

In gluon/globals.py: lines 1237 to 1241
dd = dict(locked=0,
                  client_ip=response.session_client,
                  modified_datetime=request.now.isoformat(),
                  session_data=session_pickled,
                  unique_key=unique_key)

And in python376\lib\sqlite3\dbapi2.py:
datepart, timepart = val.split(b" ")

The datetme.isoformat() string can't split wiht b" "

**Comment by davidorme** [comment]
Ha. I just came here to report the same bug. I'm moving to sessions in DB to avoid session files using up all my inodes on an application running on AWS Lightserver and found exactly the same problem. 

My setup is:

2.20.4-stable+timestamp.2020.05.03.05.18.50
(Running on nginx/1.14.0, Python 3.6.9)

I have the same diagnosis as @javitgarcia: the table is defined (https://github.com/web2py/web2py/blob/master/gluon/globals.py#L956) with:

```python
                db.define_table(
                    tname,
                    Field('locked', 'boolean', default=False),
                    Field('client_ip', length=64),
                    Field('created_datetime', 'datetime',
                          default=request.now),
                    Field('modified_datetime', 'datetime'),
                    Field('unique_key', length=64),
                    Field('session_data', 'blob'),
                    migrate=table_migrate,
                )
```

But the line at https://github.com/web2py/web2py/blob/master/gluon/globals.py#L1247 fills that with an isoformatted datetime:

```python
        dd = dict(locked=0,
                  client_ip=response.session_client,
                  modified_datetime=request.now.isoformat(),
                  session_data=session_pickled,
                  unique_key=unique_key)
```

The end result is that the DB row looks like:

```sql
sqlite> select * from web2py_session_xxxxxxxx;
               id = 2
           locked = F
        client_ip = 127.0.0.1
 created_datetime = 2021-07-29 09:42:47
modified_datetime = 2021-07-29T09:42:47.539844
       unique_key = d72b1a13-0229-44d3-b41e-8a8c3a366894
     session_data = gASVIwAAAAAAAACMDWdsdW9uLmdsb2JhbHOUjAdTZXNzaW9ulJOUfZSFlFKULg==
```

And that can't be split into date and time parts. If I manually edit the DB to remove that T, it works again, and looking at the resulting Row, that preserves the microseconds:

```python
In [1]: rws=db(db.web2py_session_silwood_masters).select()                                                                                
In [2]: rws.as_dict()                                                                                                                     
Out[2]: 
{2: {'id': 2,
  'locked': False,
  'client_ip': '127.0.0.1',
  'created_datetime': datetime.datetime(2021, 7, 29, 9, 42, 47),
  'modified_datetime': datetime.datetime(2021, 7, 29, 9, 42, 47, 539844),
  'unique_key': 'd72b1a13-0229-44d3-b41e-8a8c3a366894'}}
```
 I'm guessing here that the decimal seconds are used here to give better time resolution on updates? I think that simply replacing `request.now.isoformat()` with `str(request.now)` retains the same information and resolves the bug:

 ```python
In [12]: str(rws[0].modified_datetime)                                                                                                    
Out[12]: '2021-07-29 09:42:47.539844'
```

That patch works on my local installation.
