### ISSUE TITLE
Web2Py with Python3, https enabled on Ubuntu 18.04 (Azure VM) Bad file descriptor error

### ISSUE THREAD

**Issue by danielknobe** [web2py/web2py#2331]
**Describe the bug**
Web2Py is unusable with:
- python3
- https enabled
- Ubuntu 18.04 (Azure VM) 

The following error occurs for each thread and whole page gets stuck:
```
...
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/ico/web2py/gluon/rocket.py", line 1268, in run
    conn = Connection(*conn)
  File "/home/ico/web2py/gluon/rocket.py", line 105, in __init__
    self.socket.settimeout(SOCKET_TIMEOUT)
OSError: [Errno 9] Bad file descriptor
...
```
Same works great with python2.

**To Reproduce**
1. Fresh install of Ubuntu 18.04 (tried on Azure VM)
2. Configure https (nothing special here)
3. run web2py.py
4. clicking around, opening some admin pages

**Desktop**
 - OS:  Ubuntu 18.04 (Azure VM)
 - Python 3.6 or Python 3.7 (tested both versions)
 - Web2Py Version 2.20.4-stable+timestamp.2020.05.03.05.18.50

**Comment by feequs** [comment]
same here

**Comment by npnmos** [comment]
Same here, only difference is that i am using Ubuntu 18.04 inside Docker. 
I saw that Chrome gives issues, while Firefox works.
I have found this link [https://groups.google.com/g/web2py/c/88cdjtdc80Y]() pointing to [https://www.bountysource.com/issues/90475877-w-solution-python-3-ssl-rocket-error-on-windows-oserror-winerror-10038-an-operation-was-attempted-on-something-that-is-not-a-socket]().
I have tried the workaround and now it works but i get these messages on the console (when using Chrome): 
```
ERROR:Rocket.Errors.Thread-2:Tried to send "400 Bad Request" to client but received socket error
ERROR:Rocket.Errors.Thread-10:Tried to send "400 Bad Request" to client but received socket error
ERROR:Rocket.Errors.Thread-9:Tried to send "400 Bad Request" to client but received socket error
ERROR:Rocket.Errors.Thread-4:Tried to send "400 Bad Request" to client but received socket error
ERROR:Rocket.Errors.Thread-5:Tried to send "400 Bad Request" to client but received socket error
```

**Comment by MaxGyver83** [comment]
I get the same error message as @danielknobe (after some days). I'm running web2py 2.21.1-stable in a Ubuntu 18.04 docker container.
