### ISSUE TITLE
No driver of supported ones - for postgres

### ISSUE THREAD

**Issue by icreator** [web2py/web2py#2359]
PostgreSQL 9.5 vers

**Describe the bug**

```
127.0.0.1.2020-11-06.15-37-10.ae621685-5439-4185-b8ae-e6e5b4b3b351
<type 'exceptions.RuntimeError'> Failure to connect, tried 5 times: Traceback (most recent call last): File "/home/www-data/web2py/gluon/packages/dal/pydal/base.py", line 507, in __init__ self._adapter = adapter(**kwargs) File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/postgres.py", line 28, in __call__ return AdapterMeta.__call__(cls, *args, **kwargs) File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 41, in __call__ obj = super(AdapterMeta, cls).__call__(*args, **kwargs) File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/postgres.py", line 67, in __init__ after_connection, File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 417, in __init__ super(SQLAdapter, self).__init__(*args, **kwargs) File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 85, in __init__ self.find_driver() File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 134, in find_driver "No driver of supported ones %s is available" % str(self.drivers) RuntimeError: No driver of supported ones ('psycopg2',) is available
Version
web2py™ 	Version 2.20.4-stable+timestamp.2020.05.03.05.18.50
Traceback

Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/www-data/web2py/applications/7pay_in/models/db.py", line 39, in <module>
    fake_migrate = fake_migrate,
  File "/home/www-data/web2py/gluon/packages/dal/pydal/base.py", line 209, in __call__
    obj = super(MetaDAL, cls).__call__(*args, **kwargs)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/base.py", line 526, in __init__
    "Failure to connect, tried %d times:\n%s" % (attempts, tb)
RuntimeError: Failure to connect, tried 5 times:
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/packages/dal/pydal/base.py", line 507, in __init__
    self._adapter = adapter(**kwargs)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/postgres.py", line 28, in __call__
    return AdapterMeta.__call__(cls, *args, **kwargs)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 41, in __call__
    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/postgres.py", line 67, in __init__
    after_connection,
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 417, in __init__
    super(SQLAdapter, self).__init__(*args, **kwargs)
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 85, in __init__
    self.find_driver()
  File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 134, in find_driver
    "No driver of supported ones %s is available" % str(self.drivers)
RuntimeError: No driver of supported ones ('psycopg2',) is available

In file: /home/www-data/web2py/applications/7pay_in/models/db.py

1. <code object <module> at 0x7fba5909a430, file "/home/www-data/web2py/applications/7pay_in/models/db.py", line 7>

```
**In Code**
```
db = DAL(myconf.take('db.uri'), pool_size=myconf.take('db.pool_size', cast=int), check_reserved=['all'],
                #migrate = Not (Not (myconf.take('db.migrate'))),
                migrate = migrate,
                fake_migrate = fake_migrate,
                )
```
private/appconfig.ini:
```
uri       = postgres://www-data:1@localhost:5432/7pay_in
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5246904/98367757-3a6e3500-2047-11eb-853f-450cb2049402.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20

psycopg2 installed!

![image](https://user-images.githubusercontent.com/5246904/98403076-702c1180-2079-11eb-918d-8391eaed830e.png)

**Comment by leonelcamara** [comment]
You need to install psycopg2

     pip install psycopg2

**Comment by icreator** [comment]
I run 

sudo apt-get -y install python-psycopg2

and restart service

but error stil exist

**Comment by icreator** [comment]
may be PostgreSQL 9.5 vers becouse?

**Comment by icreator** [comment]
do reboot !
