### ISSUE TITLE
web2py does not support MySQL, using mysql URI in DAL parameter breaks application

### ISSUE THREAD

**Issue by paralaks** [web2py/web2py#2390]
**Describe the bug**
Changing database uri in appconfig ini file only breaks application. Mysql support does not exist beyond loading mysql drivers/libraries. 

**To Reproduce**
Change DAL uri to mysql as described in the documentation 

**Expected behavior**
Application does not work.

**Desktop (please complete the following information):**
Ubuntu 20

**Comment by jpsteil** [comment]
What kind of errors are you seeing?  I've been using web2py with MySQL since 2011 and it has always worked well.

**Comment by paralaks** [comment]
I have deleted it and won't go back to it. But eventually with latest stable version of web2py and latest mysql version on ubuntu, any application I have created with web2py admin ended up getting broken once I have updated DAL uri. Database connection would succeed, however, no auth tables were being created and I got a ticket link with an error compaining about a key in collection missing or something. I won't be able to provide anything more at the moment, sorry. I was trying to help a friend to switch from sqllite to mysql. (What a terrible idea to start a project with sqllite by the way!)

**Comment by jpsteil** [comment]
If you switched the URI, did you clean out the databases directory so that the migration would recreate all tables?  Migration information is stored in the databases directory.  If you change the URI, the old information is still there and it won't rerun the migration until that dir is cleared out.

**Comment by paralaks** [comment]
Just cloned and created a test application hoping that it would work this time. Deleted everything in databases directory, updated uri in appconfig.ini and hit database administration button. Got a ticket link which had the trace below. 

Error ticket for "mysql_test"
Ticket ID
127.0.0.1.2021-08-02.17-46-29.941ba9e0-6c28-40cb-8ed3-fd030a0e5013

<class 'KeyError'> 255
Version
web2py™	Version 2.21.1-stable+timestamp.2020.11.27.18.21.43
Python	Python 3.8.10: /usr/bin/python (prefix: /usr)
Traceback


Traceback (most recent call last):
  File "/home/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/web2py/applications/mysql_test/models/db.py", line 95, in <module>
    auth.define_tables(username=False, signature=False)
  File "/home/web2py/gluon/tools.py", line 2100, in define_tables
    super(Auth, self).define_tables(username, signature, migrate, fake_migrate)._table_signature_list
  File "/home/web2py/gluon/authapi.py", line 322, in define_tables
    db.define_table(
  File "/home/web2py/gluon/packages/dal/pydal/base.py", line 679, in define_table
    table = self.lazy_define_table(tablename, *fields, **kwargs)
  File "/home/web2py/gluon/packages/dal/pydal/base.py", line 716, in lazy_define_table
    self._adapter.create_table(
  File "/home/web2py/gluon/packages/dal/pydal/adapters/base.py", line 943, in create_table
    return self.migrator.create_table(*args, **kwargs)
  File "/home/web2py/gluon/packages/dal/pydal/migrator.py", line 337, in create_table
    self.adapter.create_sequence_and_triggers(query, table)
  File "/home/web2py/gluon/packages/dal/pydal/adapters/base.py", line 1027, in create_sequence_and_triggers
    self.execute(query)
  File "/home/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 65, in wrap
    if not args[0].connection:
  File "/home/web2py/gluon/packages/dal/pydal/connection.py", line 32, in connection
    return self.get_connection()
  File "/home/web2py/gluon/packages/dal/pydal/connection.py", line 65, in get_connection
    connection = self.connector()
  File "/home/web2py/gluon/packages/dal/pydal/adapters/mysql.py", line 64, in connector
    conn = self.driver.connect(**self.driver_args)
  File "/home/web2py/gluon/contrib/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/home/web2py/gluon/contrib/pymysql/connections.py", line 688, in __init__
    self.connect()
  File "/home/web2py/gluon/contrib/pymysql/connections.py", line 905, in connect
    self._get_server_information()
  File "/home/web2py/gluon/contrib/pymysql/connections.py", line 1231, in _get_server_information
    self.server_charset = charset_by_id(lang).name
  File "/home/web2py/gluon/contrib/pymysql/charset.py", line 38, in by_id
    return self._by_id[id]
KeyError: 255

**Comment by leonelcamara** [comment]
Looks like a problem with the web2py included pymysql, can you guys run

    python3 -m pip install PyMySQL

restart web2py, and try again?

**Comment by paralaks** [comment]
It worked! Thank you for your assistance. 
Not sure who would be doing but it would be nice to have this in some sort of troubleshooting section of documentation. Also cleaning up databases folder after changing uri would be almost impossible to figure out for someone who is new to python.
