### ISSUE TITLE
isAlive error

### ISSUE THREAD

**Issue by fcbarnard** [web2py/web2py#2391]
I received the following error in the terminal.

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/fcbarnard/Documents/development/web2py/gluon/widget.py", line 570, in stop
    self.server.stop()
  File "/home/fcbarnard/Documents/development/web2py/gluon/main.py", line 792, in stop
    self.server.stop(stoplogging)
  File "/home/fcbarnard/Documents/development/web2py/gluon/rocket.py", line 743, in stop
    if l.isAlive():
  File "/home/fcbarnard/Documents/development/web2py/gluon/rocket.py", line 537, in isAlive
    return self.thread.isAlive()
AttributeError: 'Thread' object has no attribute 'isAlive'

It is the same isAlive error I received earlier. I am running the latest version available in GitHub

Any suggestions on how to fix it

**Comment by fcbarnard** [comment]
I got it working
