### ISSUE TITLE
Version 2.22.1 is missing pyDAL

### ISSUE THREAD

**Issue by bnmnetp** [web2py/web2py#2421]
**Describe the bug**
I did my usual install script and 

**To Reproduce**
1. install web2py_src.zip from pythonanywhere
2. try to start up web2py

```
Traceback (most recent call last):
production-runestone-1  |   File "/srv/web2py/gluon/__init__.py", line 31, in import_packages
production-runestone-1  |     sys.modules[package] = __import__(package)
production-runestone-1  | ModuleNotFoundError: No module named 'pydal'
production-runestone-1  |
production-runestone-1  | During handling of the above exception, another exception occurred:
production-runestone-1  |
production-runestone-1  | Traceback (most recent call last):
production-runestone-1  |   File "<string>", line 1, in <module>
production-runestone-1  |   File "/srv/web2py/gluon/__init__.py", line 35, in <module>
production-runestone-1  |     import_packages()
production-runestone-1  |   File "/srv/web2py/gluon/__init__.py", line 33, in import_packages
production-runestone-1  |     raise RuntimeError(MESSAGE % package)
production-runestone-1  | RuntimeError: web2py depends on pydal, which apparently you have not installed.
production-runestone-1  | Probably you cloned the repository using git without '--recursive'
production-runestone-1  | To fix this, please run (from inside your web2py folder):
production-runestone-1  |
production-runestone-1  |      git submodule update --init --recursive
production-runestone-1  |
production-runestone-1  | You can also download a complete copy from http://www.web2py.com.
```

**Expected behavior**
web2py starts successfully

**Comment by jdavidbakr** [comment]
Started getting this today on my docker builds as well.

**Comment by mmoye** [comment]
Having this exact same issue installing https://raw.githubusercontent.com/web2py/web2py/master/scripts/setup-web2py-nginx-uwsgi-ubuntu-focal.sh on linux
