### ISSUE TITLE
Web2py downloaded from website does not find dal

### ISSUE THREAD

**Issue by LukasJerabek** [web2py/web2py#2443]
**Describe the bug**
Looks like a bug that was here recently with release few months ago. Web2py downloaded from official website does not include dal.

**To Reproduce**
1. update to latest web2py downloading from https://mdipierro.pythonanywhere.com/examples/static/web2py_src.zip
2. restart process.

**Expected behavior**

**Traceback**

> Traceback (most recent call last):
>   File "~/xxx/web2py/gluon/__init__.py", line 31, in import_packages
>     sys.modules[package] = __import__(package)
> ModuleNotFoundError: No module named 'pydal'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "~/xxx/web2py/wsgihandler.py", line 29, in <module>
>     from gluon.settings import global_settings
>   File "~/xxx/web2py/gluon/__init__.py", line 35, in <module>
>     import_packages()
>   File "~/xxx/web2py/gluon/__init__.py", line 33, in import_packages
>     raise RuntimeError(MESSAGE % package)
> RuntimeError: web2py depends on pydal, which apparently you have not installed.
> Probably you cloned the repository using git without '--recursive'
> To fix this, please run (from inside your web2py folder):
> 
>      git submodule update --init --recursive

**Desktop (please complete the following information):**
 - OS: centos7
 - Web2py version 2.22.4

**Comment by macfiron** [comment]
Additional information: When trying to clone the git repo or to update the submodules, dal packages fails:
either try git clone --recursive https://github.com/web2py/web2py.git
or git submodule update --init --recursive
and get:
[...]
fatal: remote error: upload-pack: not our ref 64ed5e7a7b4314b18bd9a5cf474f5c6cb7f75e77
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'gluon/packages/dal', but it did not contain 64ed5e7a7b4314b18bd9a5cf474f5c6cb7f75e77. Direct fetching of that commit failed.

**Comment by h4ttori** [comment]
Any advance on this issue? can anybody help me to install web2py?

**Comment by LukasJerabek** [comment]
git clone https://github.com/web2py/web2py

 cd web2py

 use "git checkout <commit id>" to checkout one commit below commit with text "version 2.22.4 + pydal upgrade"

 git submodule update --init --recursive

**Comment by LukasJerabek** [comment]
> If you want you can install it by hand, just run: `pip install pydal`
> 
> Or download this source: https://mdipierro.pythonanywhere.com/examples/static/web2py_src.zip
> 
> The source is found on http://web2py.com/init/default/download under "Python 3.7" > Source Code.
> 
> Just checked and the latest zip contains the dal (and yatl) module.

Thats exactly what this issue is about. Its not working.

**Comment by jicho** [comment]
When that's the case I would go for `pip install pydal`.
That always works form me.

Another advantage is that you can use the latest version whenever you want.

**Comment by LukasJerabek** [comment]
I did not try that this time, but last time other issues rose up, with yatl and so on, I have tried to install other packages that it complained about when I got to error I did not know what to dowload any more and it did not work as well. But Jicho sure can try that...

**Comment by jicho** [comment]
Okay... in my experience you need:
`pip install pydal` (DAL support)
`pip install yatl` (HTML templates)

and based on your system you might need `pip install pymysql` when you're using Web2Py in combination with MySQL and the module isn't already on your system.

In my case everything starts the last time I've started from scratch.
