### ISSUE TITLE
Scheduler does not exit on OperationalError

### ISSUE THREAD

**Issue by dlage** [web2py/web2py#2465]
Scheduler process does not exit when caught in an OperationalError. This leaves the process inactive for the farm but systemd sees it as active, which makes it necessarily to manually restart the scheduler to recover operations.
In other cases, exit is done but the exit status used it 0 which make systemd see it as a "clean exit".

Logs:
```
Mar 27 10:17:18 server-hostname python[71337]: ERROR:web2py.scheduler.server-hostname#71337:Error retrieving status
Mar 27 10:17:18 server-hostname python[71337]: Traceback (most recent call last):
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/scheduler.py", line 1255, in send_heartbeat
Mar 27 10:17:18 server-hostname python[71337]:     db.commit()
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/packages/dal/pydal/base.py", line 800, in commit
Mar 27 10:17:18 server-hostname python[71337]:     self._adapter.commit()
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 58, in wrap
Mar 27 10:17:18 server-hostname python[71337]:     return f(*args, **kwargs)
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 985, in commit
Mar 27 10:17:18 server-hostname python[71337]:     return self.connection.commit()
Mar 27 10:17:18 server-hostname python[71337]: psycopg2.OperationalError: server closed the connection unexpectedly
Mar 27 10:17:18 server-hostname python[71337]: #011This probably means the server terminated abnormally
Mar 27 10:17:18 server-hostname python[71337]: #011before or while processing the request.
Mar 27 10:17:18 server-hostname python[71337]: Exception in thread Thread-1:
Mar 27 10:17:18 server-hostname python[71337]: Traceback (most recent call last):
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/scheduler.py", line 1255, in send_heartbeat
Mar 27 10:17:18 server-hostname python[71337]:     db.commit()
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/packages/dal/pydal/base.py", line 800, in commit
Mar 27 10:17:18 server-hostname python[71337]:     self._adapter.commit()
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 58, in wrap
Mar 27 10:17:18 server-hostname python[71337]:     return f(*args, **kwargs)
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 985, in commit
Mar 27 10:17:18 server-hostname python[71337]:     return self.connection.commit()
Mar 27 10:17:18 server-hostname python[71337]: psycopg2.OperationalError: server closed the connection unexpectedly
Mar 27 10:17:18 server-hostname python[71337]: #011This probably means the server terminated abnormally
Mar 27 10:17:18 server-hostname python[71337]: #011before or while processing the request.
Mar 27 10:17:18 server-hostname python[71337]: During handling of the above exception, another exception occurred:
Mar 27 10:17:18 server-hostname python[71337]: Traceback (most recent call last):
Mar 27 10:17:18 server-hostname python[71337]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Mar 27 10:17:18 server-hostname python[71337]:     self.run()
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/scheduler.py", line 792, in run
Mar 27 10:17:18 server-hostname python[71337]:     self.send_heartbeat(counter)
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/scheduler.py", line 1258, in send_heartbeat
Mar 27 10:17:18 server-hostname python[71337]:     db.rollback()
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/packages/dal/pydal/base.py", line 804, in rollback
Mar 27 10:17:18 server-hostname python[71337]:     self._adapter.rollback()
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 58, in wrap
Mar 27 10:17:18 server-hostname python[71337]:     return f(*args, **kwargs)
Mar 27 10:17:18 server-hostname python[71337]:   File "/home/www-data/web2py/gluon/packages/dal/pydal/adapters/base.py", line 989, in rollback
Mar 27 10:17:18 server-hostname python[71337]:     return self.connection.rollback()
Mar 27 10:17:18 server-hostname python[71337]: psycopg2.InterfaceError: connection already closed
```

**Comment by leonelcamara** [comment]
> doesn't the connection get automatically resumed ?

@niphlod no not in our tests. The scheduler process will crash and web2py will return 0 so systemd doesn't restart it.

**Comment by niphlod** [comment]
then I'd investigate why the connection doesn't get restored. Theoretically it's DAL's responsibility to open a new connection, unless attempts=0 is passed in the settings.

**Comment by niphlod** [comment]
yeah, the point is that the scheduler *should* remain alive, and re-loop over hopefully gaining a new/fresh connection from the pool. That's the deal I was trying to explain discerning "terminating" vs "non-terminating" errors. If you want the scheduler to shut down with sys.exit(1) on any "non-terminating" errors, because pydal isn't able to acquire a new/fresh connection, and you rely on having an external thingy (systemd) to prop up a fresh scheduler process so you're sure tasks can be processed, go for it, but bear in mind that not everybody has "the external thingy", and killing the scheduler on "non-terminating" errors may be overkill.

**Comment by leonelcamara** [comment]
@niphlod could we simply do a ````self.db.get_connection_from_pool_or_new()```` inside the loop so it tries to reconnect?
