### ISSUE TITLE
web2py 3.0.9 hangs

### ISSUE THREAD

**Issue by danielevalesani** [web2py/web2py#2510]
Hi,

I tried to download revision 3.0.9 and I see a problem. Previously I was using revision 2.27.1.
The most obvious issues are in the login of all the web apps. They hangs all the time.

**Comment by danielevalesani** [comment]
below the log under cmd

ERROR:Rocket.Errors.Thread-3:Traceback (most recent call last):

  File "E:\...\...\web2py\gluon\packages\rocket3\rocket3\__init__.py", line 1165, in run
    self.run_app(conn)

  File "E:\...\...\web2py\gluon\packages\rocket3\rocket3\__init__.py", line 1651, in run_app
    self.environ = environ = self.build_environ(sock_file, conn)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\...\...\web2py\gluon\packages\rocket3\rocket3\__init__.py", line 1468, in build_environ
    request = self.read_request_line(sock_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\...\...\web2py\gluon\packages\rocket3\rocket3\__init__.py", line 1213, in read_request_line
    d = sock_file.readline()
        ^^^^^^^^^^^^^^^^^^^^

  File "D:\...\Python312\Lib\socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^

ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

ERROR:Rocket.Errors.Thread-3:Tried to send "500 Server Error" to client but received socket error

**Comment by danielevalesani** [comment]
It seems to be a problem of caching. I refreshed the web page in the browser using F5 keyword and I was able end succesfully the authentication process. However, the web app hangs navigating any web page of the website. If I clean the folder "sessions", the web app start hanging again from the login process.

**Comment by nicozanf** [comment]
I also have the same problem on windows, and a similar behaviour (but without any error) on Linux and MacOs. See also issue #2507

**Comment by nicozanf** [comment]
should be fixed by a simple change on rocket3, see https://github.com/web2py/rocket3/pull/5 . Can you confirm?

**Comment by nicozanf** [comment]
I think it's fixed by version 3.0.11 and can be closed

**Comment by danielevalesani** [comment]
the issue is fully fixed with the version 3.0.11
