### ISSUE TITLE
SQLFORM.grid/SQLTABLE does not work without "id" field

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#605]
_From [ochib...@gmail.com](https://code.google.com/u/107398878481677837585/) on December 01, 2011 16:31:53_

What steps will reproduce the problem? 1. Create table without id field but another primary key field
2. Define table using primarykey
3. Create SQLFORM.grid or SQLTABLE just like you normally do What is the expected output? What do you see instead? They are great features and I want them to support primarykey. Otherwise, you can not really use the existing tables for it. In my case, no tables has "id" field. What version of the product are you using? On what operating system? Version 1.99.2
Tested with DB2 and SQL Server 2008 Please provide any additional information below. https://groups.google.com/group/web2py/browse_thread/thread/f069cefe96e0e08a/844522760b98572f?lnk=gst&q=What&#37;27s+the+best+way+to+paginate+without+SQLFORM.gird+&#37;3F+Options+#844522760b98572f

_Original issue: http://code.google.com/p/web2py/issues/detail?id=547_

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on December 04, 2011 14:04:01_

This is a big can of worms. I will not happen soon

**Status:** Accepted

**Comment by niphlod** [comment]
_From [massimo....@gmail.com](https://code.google.com/u/111721297562664670951/) on August 07, 2012 12:17:26_

I believe this was fixed. Can you check?

**Comment by niphlod** [comment]
_From [ochib...@gmail.com](https://code.google.com/u/107398878481677837585/) on August 07, 2012 13:41:26_

Nope.

I tested but I got a following error.

Traceback (most recent call last):
  File "C:\trunk\web2py\gluon\restricted.py", line 205, in restricted
    exec ccode in environment
  File "C:/trunk/web2py/applications/test/controllers/default.py", line 68, in \<module>
  File "C:\trunk\web2py\gluon\globals.py", line 182, in \<lambda>
    self._caller = lambda f: f()
  File "C:/trunk/web2py/applications/test/controllers/default.py", line 13, in index
    grid = SQLFORM.grid(db.EDTPOH00.PODOCS!="")
  File "C:\trunk\web2py\gluon\sqlhtml.py", line 1606, in grid
    field_id = tables[0]._id
  File "C:\trunk\web2py\gluon\dal.py", line 7448, in __getattr__
    return self[key]
  File "C:\trunk\web2py\gluon\dal.py", line 7388, in __getitem__
    return dict.__getitem__(self, str(key))

Models/db_table.py
\-------------------------------------------------------------------
db.define_table('EDTPOH00',
    Field('POIMHF', length=1),
    Field('PODOCS', length=3),
    Field('POCTRL', length=20),
    Field('PODIID', length=5),
    Field('PODICD', length=20),
    Field('PODDNO', length=22),
    Field('POJDNO', length=8),
    primarykey=['PODOCS', 'POCTRL', 'PODIID', 'PODICD','PODDNO'])
\-------------------------------------------------------------------

Controller/default.py
\-------------------------------------------------------------------
def index():
    grid = SQLFORM.grid(db.EDTPOH00.PODOCS!="")
    return dict(grid=grid)
\-------------------------------------------------------------------

Views/default/index.html
\-------------------------------------------------------------------
{{left_sidebar_enabled,right_sidebar_enabled=False,True}}
{{extend 'layout.html'}}

{{=grid}}
\-------------------------------------------------------------------

**Comment by niphlod** [comment]
_From [ochib...@gmail.com](https://code.google.com/u/107398878481677837585/) on August 07, 2012 13:47:31_

I tested with "Version 2.0.0 (2012-08-07 14:30:28) dev"
