### ISSUE TITLE
Appadmin viewing one records results in an error

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#688]
_From [remco.boerma](https://code.google.com/u/remco.boerma/) on December 19, 2013 12:12:22_

When i use appadmin to view JobPlatform table and i click on a single row to view that entry i get an error.  

I open https://lvwaso01.rocdc.local/dc_jobs/appadmin/update/db/JobPlatform/3 and get: 
\<class 'pyodbc.ProgrammingError'> ('42000', "[42000] [FreeTDS][SQL Server]Column 'Platform.ApplicationDomain' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. (8120) (SQLExecDirectW)")

The error is about Platform.ApplicationDomain while i'm looking at JobPlatform table. That was a little odd to me. It might be because of the foreign key constraint, but then i don't know why application domain is used in an aggregate function. 

Here's the full traceback:
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 217, in restricted
    exec ccode in environment
  File "/home/www-data/web2py/applications/dc_jobs/controllers/appadmin.py", line 654, in \<module>
  File "/home/www-data/web2py/gluon/globals.py", line 372, in \<lambda>
    self._caller = lambda f: f()
  File "/home/www-data/web2py/applications/dc_jobs/controllers/appadmin.py", line 342, in update
    f='download', args=request.args[:1]))
  File "/home/www-data/web2py/gluon/sqlhtml.py", line 1145, in __init__
    inp = self.widgets.options.widget(field, default)
  File "/home/www-data/web2py/gluon/sqlhtml.py", line 270, in widget
    options = requires[0].options()
  File "/home/www-data/web2py/gluon/validators.py", line 559, in options
    self.build_set()
  File "/home/www-data/web2py/gluon/validators.py", line 545, in build_set
    records = self.dbset(table).select(*fields, **dd)
  File "/home/www-data/web2py/gluon/dal.py", line 10335, in select
    return adapter.select(self.query,fields,attributes)
  File "/home/www-data/web2py/gluon/dal.py", line 1831, in select
    return self._select_aux(sql,fields,attributes)
  File "/home/www-data/web2py/gluon/dal.py", line 1796, in _select_aux
    self.execute(sql)
  File "/home/www-data/web2py/gluon/dal.py", line 1916, in execute
    return self.log_execute(*a, **b)
  File "/home/www-data/web2py/gluon/dal.py", line 1910, in log_execute
    ret = self.cursor.execute(command, *a[1:], **b)
ProgrammingError: ('42000', "[42000] [FreeTDS][SQL Server]Column 'Platform.ApplicationDomain' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. (8120) (SQLExecDirectW)")

Troling uptward through the traceback i noticed that at File /home/www-data/web2py/gluon/validators.py in build_set at line 54 in the variables there is a group by defined:
dd: {'cache': None, 'cacheable': True, 'distinct': None, 'groupby': 'Platform.Straat', 'orderby': 'Platform.DocumentationLink'}
before that i didn't see it. 

Here's my model: 

VarcharMax = SQLCustomType(
     type ='text', # web2py type
     native='varchar(max)',
 )

db.define_table("Job",
      SQLField("Description", VarcharMax, notnull=True, default=''),
      SQLField("DocumentationLink", VarcharMax, default=''))

db.define_table("Platform",
      SQLField("ApplicationDomain", "string", length=30, notnull=True, default=None),
      SQLField("ServerName", "string", length=100, notnull=True, default=None),
      SQLField("DocumentationLink", VarcharMax, default=''),
      SQLField("Straat", "string", length=3, notnull=True, default=None),
      format='&#37;(ApplicationDomain)s:&#37;(ServerName)s')

db.define_table("JobPlatform",
      SQLField("id_Job", db.Job),
      SQLField("id_Platform", db.Platform),
      SQLField("SecurityContext", "string", length=100, notnull=True, default=None),
      SQLField("LocalIdentifier", "string", length=300, notnull=True, default=None),
      SQLField("Description", VarcharMax, notnull=True, default=None),
      SQLField("DocumentationLink", VarcharMax, default=None),
      format='&#37;(id_platform)s') 

I'm using revision f8df8f614cff (2.8.2)  (and not the latest from trunk because that breaks because of the sql server escaping)

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1829_

**Comment by niphlod** [comment]
not sure when, but just tested this and can't reproduce.
