### ISSUE TITLE
'ascii' codec can't encode character error on list:string DAL

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#697]
_From [firstcla..._at_gmail.com](https://code.google.com/u/114641566817690199919/) on March 07, 2014 05:47:17_

What steps will reproduce the problem? 1. Saving strings containing special latin characters to list:string will give an error.
[u'Higher School Justiniani i Par\xeb', u'Higher School Justiniani i Par\xeb'] What is the expected output? What do you see instead? Throws Error ticket.
\<type 'exceptions.UnicodeEncodeError'> 'ascii' codec can't encode character u'\xeb' in position 30: ordinal not in range(128) What version of the product are you using? On what operating system? 2.8.2-stable+timestamp.2013.11.28.13.54.07
(Running on Apache/2.2.22 (Ubuntu), Python 2.7.3) Please provide any additional information below. 1. 2. 3. 4.
5.
6.
7.
8.
9.
10.
11.
12.
13.
14.
15.
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 217, in restricted
    exec ccode in environment
  File "/home/www-data/web2py/applications/welcome/views/appadmin.html", line 189, in \<module>
    \</p>
  File "/home/www-data/web2py/gluon/sqlhtml.py", line 3012, in __init__
    r = represent(field, r or [], record)
  File "/home/www-data/web2py/gluon/sqlhtml.py", line 56, in represent
    return f(value)
  File "/home/www-data/web2py/gluon/dal.py", line 9655, in list_represent
    return ', '.join(str(y) for y in x or [])
  File "/home/www-data/web2py/gluon/dal.py", line 9655, in \<genexpr>
    return ', '.join(str(y) for y in x or [])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 30: ordinal not in range(128)

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1890_

**Comment by niphlod** [comment]
_From [firstcla..._at_gmail.com](https://code.google.com/u/114641566817690199919/) on March 06, 2014 20:51:38_

I forgot to include one additional information.
I am running MongoDB.

**Comment by ProjectGuerilla** [comment]
I can also report that I am having a similar issue when using postgres - I don't think that this issue is db related. 

For me, attempting to insert a list of unicode strings into a postgres list:string Field is generating this stack trace:
    Traceback (most recent call last):
      File "/Users/ops/PycharmProjects/testbed/bs_prod_tools/mpx_rss_reader.py", line 165, in <module>
        db.metadatatable.update_or_insert(db.metadatatable.guid==item['guid'],**item)
      File "/Users/ops/virtualenvs/py276/lib/python2.7/site-packages/pydal/objects.py", line 801, in update_or_insert
        record.update_record(**values)
      File "/Users/ops/virtualenvs/py276/lib/python2.7/site-packages/pydal/helpers/classes.py", line 162, in __call__
        table._db(table._id==id,ignore_common_filters=True).update(**newfields)
      File "/Users/ops/virtualenvs/py276/lib/python2.7/site-packages/pydal/objects.py", line 2095, in update
        ret = db._adapter.update("%s" % table._tablename,self.query,fields)
      File "/Users/ops/virtualenvs/py276/lib/python2.7/site-packages/pydal/adapters/base.py", line 967, in update
        sql = self._update(tablename, query, fields)
      File "/Users/ops/virtualenvs/py276/lib/python2.7/site-packages/pydal/adapters/base.py", line 962, in _update
        for (field, value) in fields])
      File "/Users/ops/virtualenvs/py276/lib/python2.7/site-packages/pydal/adapters/base.py", line 907, in expand
        return str(self.represent(expression,field_type))
      File "/Users/ops/virtualenvs/py276/lib/python2.7/site-packages/pydal/adapters/postgres.py", line 313, in represent
        return BaseAdapter.represent(self, obj, fieldtype)
      File "/Users/ops/virtualenvs/py276/lib/python2.7/site-packages/pydal/adapters/base.py", line 1337, in represent
        obj = map(str,obj)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 14: ordinal not in range(128)

The issue is with the map(str,obj) call where the str() call fails on unicode. If someone can suggest how to introspect the db to know what encoding is expected I can look into a fix. (this is my first look into the source so I'm looking at a lot of digging to find a way forward.)

**Comment by niphlod** [comment]
this has been fixed
