### ISSUE TITLE
cache.action broken on GAE

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#720]
_From [richar..._at_gmail.com](https://code.google.com/u/112985171729633859941/) on August 28, 2014 09:21:35_

I used this to cache a controller method:
__at__cache.action(time_expire=300, cache_model=cache.ram, session=False, vars=False, public=True)

Works fine on standard web2py but under GAE:

Traceback (most recent call last):
  File "/home/hoju/web2py/gluon/restricted.py", line 220, in restricted
    exec ccode in environment
  File "/home/hoju/web2py/applications/places/controllers/default.py", line 103, in \<module>
  File "/home/hoju/web2py/gluon/globals.py", line 385, in \<lambda>
    self._caller = lambda f: f()
  File "/home/hoju/web2py/gluon/cache.py", line 510, in wrapped_f
    rtn = cache_model(cache_key, lambda : func(), time_expire=time_expire)
  File "/home/hoju/web2py/gluon/contrib/gae_memcache.py", line 40, in __call__
    self.client.set(key, (time.time(), value), time=time_expire)
  File "/home/hoju/google_appengine/google/appengine/api/memcache/__init__.py", line 763, in set
    namespace=namespace)
  File "/home/hoju/google_appengine/google/appengine/api/memcache/__init__.py", line 868, in _set_with_policy
    time, '', namespace)
  File "/home/hoju/google_appengine/google/appengine/api/memcache/__init__.py", line 947, in _set_multi_async_with_policy
    stored_value, flags = _validate_encode_value(value, self._do_pickle)
  File "/home/hoju/google_appengine/google/appengine/api/memcache/__init__.py", line 227, in _validate_encode_value
    stored_value = do_pickle(value)
  File "/home/hoju/google_appengine/google/appengine/api/memcache/__init__.py", line 392, in _do_pickle
    pickler.dump(value)
TypeError: _decorated() takes exactly 1 argument (0 given)

_Original issue: http://code.google.com/p/web2py/issues/detail?id=1969_

**Comment by niphlod** [comment]
_From [richar..._at_gmail.com](https://code.google.com/u/112985171729633859941/) on August 28, 2014 00:22:19_

Web2py Version 2.9.5-stable+timestamp.2014.03.16.02.35.39

**Comment by mdipierro** [comment]
This looks like a GAE bug. It may have been resolved since.
