### ISSUE TITLE
Bug with forking/multiprocessing -- launch directory

### ISSUE THREAD

**Issue by niphlod** [web2py/web2py#748]
_From [rmathews_at_gmail.com](https://code.google.com/u/rmathews_at_gmail.com/) on December 20, 2014 08:06:57_

I have a weird bug that seems to be triggered when using the multiprocessing module, if web2py is launched from another directory.

I've tried to isolate the issue.  To reproduce the issue, take a clean web2py source tarball, and make the following changes:

1. to the end of applications/welcome/controllers/default.py add the lines:
	import alpha
	def bravo():
	    return alpha.charlie()

2. create a new file applications\welcome\modules\alpha.py with the following content
	from multiprocessing import Process, Manager

	def delta(output):
	    output.append('Hello, world!')

	def charlie():
	    output = Manager().list()
	    p = Process(target=delta, args=(output,))
	    p.start()
	    p.join()
	    return output[0]

3. run it normally, 
        d:\code\temp\web2py>python web2py.py
    ... hit http://127.0.0.1:8000/welcome/default/bravo ... everything works

4. change the current working directory, and relaunch
	d:\code\temp\web2py>cd ..
	d:\code\temp>python web2py\web2py.py
   and you get an error.  An unhelpful ticket, but the console has the following traceback:
	Traceback (most recent call last):
	  File "<string>", line 1, in \<module>
	  File "D:\Python27\lib\multiprocessing\forking.py", line 380, in main
	    prepare(preparation_data)
	  File "D:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
	    file, path_name, etc = imp.find_module(main_name, dirs)
	ImportError: No module named web2py

If it helps, I put a print statement before File "D:\Python27\lib\multiprocessing\forking.py", line 489, and it printed out:
        ['d:\\code\\temp\\web2py\\web2py']

Something is causing the path to add the directory web2py twice!

If I run the code from one directory above that:
	d:\code\temp>cd ..
	d:\code>python temp\web2py\web2py.py
then the following is printed:
        ['d:\\code\\temp\\web2py\\temp\\web2py']

Again the path is repeated twice.

Can anyone help me understand what is causing this issue?  What is a potential fix?

If it helps, the real bug got triggered when running web2py behind Apache on Windows (modwsgi), since the wsgi script was launched from some random Apache directory.

_Original issue: http://code.google.com/p/web2py/issues/detail?id=2030_

**Comment by niphlod** [comment]
_From [paolo.va..._at_gmail.com](https://code.google.com/u/107767337307670204068/) on December 19, 2014 23:54:36_

What's your web2py version?

**Comment by niphlod** [comment]
_From [rmathews_at_gmail.com](https://code.google.com/u/rmathews_at_gmail.com/) on December 19, 2014 23:56:32_

2.9.11, but I don't think this is a version specific issue.

Was it not reproducible at your end?

**Comment by niphlod** [comment]
_From [paolo.va..._at_gmail.com](https://code.google.com/u/107767337307670204068/) on December 23, 2014 01:19:08_

I tried on ubuntu and it worked.
I imported the alpha module by specifying the whole path:
from applications.YOUR_APP.modules.alpha import charlie

**Comment by niphlod** [comment]
_From [rmathews_at_gmail.com](https://code.google.com/u/rmathews_at_gmail.com/) on December 23, 2014 03:28:11_

Windows only.  I'm sorry, I should have mentioned that.

The forking code is different on Linux.
