### ISSUE TITLE
web2py crashes on 'session_pickled = pickle.dumps(self, pickle.HIGHEST_PROTOCOL)' with 2 instances

### ISSUE THREAD

**Issue by dmatic** [web2py/web2py#834]
I am running two instances of web2py (2.9.12-stable+timestamp.2015.01.17.06.11.03) under apache and only first started instance works, the second instance crashes with error <type 'exceptions.TypeError'>('NoneType' object is not callable)

Traceback (most recent call last):
  File "/opt/web-apps/web2py_sr/gluon/main.py", line 435, in wsgibase
    session.connect(request, response)
  File "/opt/web-apps/web2py_sr/gluon/globals.py", line 934, in connect
    session_pickled = pickle.dumps(self, pickle.HIGHEST_PROTOCOL)
TypeError: 'NoneType' object is not callable

I have another server with web2py version 2.4.5 and it works there.

**Comment by remcoboerma** [comment]
Are you trying to store something in the session that cannot be pickled? 

I've had the same issue today while move stuff between instances/servers. While I searched for anything related to the move it was some object stored in the session that bugged me.

**Comment by dmatic** [comment]
Nope, not as far as I know. It only happened when I started another instance of web2py on the same server. It worked while there was only one instance. I have reverted now to version 2.4.7 and now I have three instaces working flawlessly.

**Comment by mdipierro** [comment]
What OS? What python version? What web server?

**Comment by dmatic** [comment]
Tested on CentOS 6.5 and 7, python 2.6.6 (on centos 6.5) and python 2.7.5 (on centos 7), apache web server in both cases (version 2.2.15 on centos 6.5 and version 2.4.6 on centos 7). 
  
On both machines trying to run two web2py instances with web2py 2.9.12 gave the same result. The first acessed address worked and continued to work while the second accessed address resulted in web2py crashing with the above message. 

On both machines reverting to web2py version 2.4.5 temporarily solved the problem.

**Comment by fabrice102** [comment]
I had the same issue. I've solved it by using a different WSGI process group for each application.
If you need to use two WSGI process groups on the same VirtualHost, see http://stackoverflow.com/a/6591232.

It seems that using pickle instead of cPickle (in gluon/globals.py) is another possible workaround, but that may degrade performances a lot.

**Comment by mdipierro** [comment]
The problem was introduced when moving to HIGHEST_PROTOCOL. We could also revert that but the problem is why? Only some people are having the problem.

**Comment by dmatic** [comment]
Thanks Fabrice for the workaround advice, it helped.

**Comment by remcoboerma** [comment]
I'm having the same issue now using an application that i moved to a windows 7 desktop using the builtin webserver (no wsgi). Cleaned the app using the appadmin interface. 

Found something that might help: 

I used the following in a class 
```python
def __getattr__(self,name):
    # we don't have this as our own property, so we can fake it
    return self.payload.get(name,None)
```
but had to change it to: 

```python
def __getattr__(self,name):
    # we don't have this as our own property, so we can fake it
    # but we don't want to frustrate pickle, so skip _.*_ names.
    if name.startswith('_') and name.endswith('_'):
        raise AttributeError
    return self.payload.get(name,None)
```

An object of the class from which above method was taken was added to the session. When the pickler tries to get `__getnewargs__` property the `__getattr__` would return `None`, which is indeed not a callable. Now it raises an exception and the pickler know `__getnewargs__` is unavailable and uses `__getstate__` or `.__dict__`

This solved my issue.

**Comment by bnmnetp** [comment]
I think this really is an issue @mdipierro -- Today I suffered big time because I brought on a second server behind a load balancer for my application. The original server was running Python 3.7.5 and the new one was running 3.8.5.  It turns out that python 3.8 introduced a new protocol -- 5 -- this caused all kinds of problems in a shared database environment as the old server.  logins were crashing left and right due to an unsupported protocol!  Using DEFAULT_PROTOCOL would have avoided all of this trouble.  [so would have using identical Python's I know! but I really wouldn't expect something like this to break between point releases of Python -- and it would not have if web2py were using DEFAULT].
