### ISSUE TITLE
Cache: PicklingError: Can't pickle <type 'function'>: attribute lookup

### ISSUE THREAD

**Issue by kirsn** [web2py/web2py#858]
Discussion thread: https://groups.google.com/d/msg/web2py/sRp7b1d3sAQ/_xMLq1xbM7AJ

```
web2py™     Version 2.9.12-stable+timestamp.2015.03.19.06.51.11
Python     Python 2.7.9: C:\Users\subbaraman\Downloads\web2py_win_002\web2py\web2py.exe (prefix: D:\programs\open\python27)
Traceback


Traceback (most recent call last):
  File "C:\Users\subbaraman\Downloads\web2py_win_002\web2py\gluon\restricted.py", line 226, in restricted
    exec ccode in environment
  File "C:/Users/subbaraman/Downloads/web2py_win_002/web2py/applications/my_app/controllers/default.py", line 1107, in <module>
  File "C:\Users\subbaraman\Downloads\web2py_win_002\web2py\gluon\globals.py", line 393, in <lambda>
    self._caller = lambda f: f()
  File "C:\Users\subbaraman\Downloads\web2py_win_002\web2py\gluon\tools.py", line 3455, in f
    return action(*a, **b)
  File "C:/Users/subbaraman/Downloads/web2py_win_002/web2py/applications/my_app/controllers/default.py", line 304, in index
    orderby=_construct_orderby(), limitby=limitby, **cache_settings)
  File "C:\Users\subbaraman\Downloads\web2py_win_002\web2py\gluon\packages\dal\pydal\objects.py", line 2085, in select
    return adapter.select(self.query,fields,attributes)
  File "C:\Users\subbaraman\Downloads\web2py_win_002\web2py\gluon\packages\dal\pydal\adapters\base.py", line 1228, in select
    time_expire)
  File "C:\Users\subbaraman\Downloads\web2py_win_002\web2py\gluon\cache.py", line 428, in __call__
    self.storage[key] = (now, value)
  File "C:\Users\subbaraman\Downloads\web2py_win_002\web2py\gluon\cache.py", line 328, in __setitem__
    pickle.dump((time.time(), value), tmp, pickle.HIGHEST_PROTOCOL)
PicklingError: Can't pickle <type 'function'>: attribute lookup 
```

**Comment by kirsn** [comment]
Fixed.
