### ISSUE TITLE
dal issue on gae

### ISSUE THREAD

**Issue by rif** [web2py/web2py#902]
System: Linux keops 3.19.2-1-ARCH #1 SMP PREEMPT Wed Mar 18 16:21:02 CET 2015 x86_64 GNU/Linux
Web2py: Version 2.10.3-stable+timestamp.2015.04.02.21.42.07
GAE: release: "1.9.18"

The line that triggers the exception in my code is: 
form = crud.create(Facturi, next=URL('index'))

where Facturi:

Facturi = db.define_table('factura',
                Field('numar', notnull=True),
                ...

Traceback (most recent call last):
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/rif/Documents/webframeworks/firmoasa/applications/firmoasa/controllers/facturi.py", line 132, in <module>
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/globals.py", line 393, in <lambda>
    self._caller = lambda f: f()
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/tools.py", line 3440, in f
    return action(*a, **b)
  File "/home/rif/Documents/webframeworks/firmoasa/applications/firmoasa/controllers/facturi.py", line 13, in index
    form = crud.create(Facturi, next=URL('index'))
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/tools.py", line 4138, in create
    **attributes
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/tools.py", line 4057, in update
    **attributes  # contains hidden
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/sqlhtml.py", line 1232, in __init__
    inp = self.widgets.options.widget(field, default)
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/sqlhtml.py", line 290, in widget
    options = requires[0].options()
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/validators.py", line 583, in options
    self.build_set()
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/validators.py", line 569, in build_set
    records = self.dbset(table).select(*fields, **dd)
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/packages/dal/pydal/objects.py", line 2093, in select
    return adapter.select(self.query,fields,attributes)
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/packages/dal/pydal/adapters/google_adapters.py", line 487, in select
    (items, tablename, fields) = self.select_raw(query,fields,attributes)
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/packages/dal/pydal/adapters/google_adapters.py", line 379, in select_raw
    filters = self.expand(query)
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/packages/dal/pydal/adapters/google_adapters.py", line 240, in expand
    return expression.op(expression.first, expression.second)
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/packages/dal/pydal/adapters/google_adapters.py", line 256, in AND
    first = self.expand(first)
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/packages/dal/pydal/adapters/google_adapters.py", line 240, in expand
    return expression.op(expression.first, expression.second)
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/packages/dal/pydal/adapters/google_adapters.py", line 260, in AND
    return ndb.AND(first, second)
  File "/home/rif/SDKs/google_appengine/google/appengine/ext/ndb/query.py", line 558, in __new__
    ' received a non-Node instance %r' % node)
TypeError: ConjunctionNode() expects Node instances as arguments; received a non-Node instance None

**Comment by ilvalle** [comment]
Does it work with an other back-end ?
Mind that crud is no longer supported, I suggest upgrading your code in favor of sqlform/sqlform.grid

**Comment by ilvalle** [comment]
@mdipierro I suggest marking http://www.web2py.com/books/default/chapter/29/07#CRUD as no longer supported.

**Comment by rif** [comment]
sqlform behaves the same it looks like if I am commenting all the fields from the model that have a IS_IN_DB requirement the form is generated (it worked OK with 2.9.12).

I'll give an example of such fields:
 Field('firma', db.firma, requires=IS_IN_DB(db(db.firma.request_tenant==auth.user_id), db.firma.id, '%(nume)s')),
                Field('cont', 'reference cont', requires=IS_EMPTY_OR(IS_IN_DB(db((db.cont.request_tenant==auth.user_id) & (db.cont.is_active==True)), db.cont.id, '%(iban)s(%(moneda)s)'))),
                Field('client', db.client, requires=IS_IN_DB(db(db.client.request_tenant==auth.user_id), db.client.id, '%(nume)s')),

I'll test now with other backends.

**Comment by rif** [comment]
:(

When I started web2py with python2 web2py.py -a test I got another error (I usually start this app with gae dev server as I am only deploying it on gae):

<class 'cPickle.UnpicklingError'> pickle data was truncated

Version
web2py™	Version 2.10.3-stable+timestamp.2015.04.02.21.42.07
Python	Python 2.7.9: /usr/bin/python2 (prefix: /usr)

Traceback (most recent call last):
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/rif/Documents/webframeworks/firmoasa/applications/firmoasa/models/facturi.py", line 82, in <module>
    format='%(denumire)s')
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/packages/dal/pydal/base.py", line 814, in define_table
    table = self.lazy_define_table(tablename,*fields,**args)
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/packages/dal/pydal/base.py", line 853, in lazy_define_table
    polymodel=polymodel)
  File "/home/rif/Documents/webframeworks/firmoasa/gluon/packages/dal/pydal/adapters/base.py", line 481, in create_table
    sql_fields_old = pickle.load(tfile)
UnpicklingError: pickle data was truncated

**Comment by ilvalle** [comment]
It's very difficult to follow your code/traceback, style your comments using markdown
Try to write the simplest snippet of code that reproduces the issue

**Comment by rif** [comment]
Well if I leave this field in the model, the form generation fails:
```python
Field('firma', db.firma, requires=IS_IN_DB(db(db.firma.request_tenant==auth.user_id), db.firma.id, '%(nume)s')),
```

**Comment by rif** [comment]
this issue is still present in 2.11.2 :(

**Comment by jparga** [comment]
I have the same  issue

**Comment by jparga** [comment]
I surrender width **IS_IN_DB** and GAE

I finally solved it width a workaround using **IS_IN_SET**:

First I get rid off IS_IN_DB in my models requirements
```Python
titulares = db(db.auth_user.tipo_usuario=='Titular')
db.t_familiares.f_titular.requires = (IS_IN_DB(titulares,'auth_user.id','%(last_name)s'+', '+ '%(first_name)s'+' - '+ '%(f_numero_socio)s',sort=True))
```

Then I build a IS_IN_SET equivalent in the controllers

```Pyhton 
titulares = db(db.auth_user.tipo_usuario == 'Titular').select(orderby=db.auth_user.last_name)
titu = []
for titulares in titulares:
      titu.append((titulares.id,titulares.last_name + ' ' + titulares.first_name + '- ' +titulares.f_numero_socio))
db.t_familiares.f_titular.requires = IS_IN_SET(titu)
form = SQLFORM(db.t_familiares)
```
So `titulares.id` is the value I get and `titulares.last_name + '  ' +titulares.first_name + '-  ' +titulares.f_numero_socio` is the dropdown value

It seems to work fine.

May be someone has a better solution

**Comment by davidmanns** [comment]
My application runs on GAE and has been stuck on 2.9.12.

Runs fine in web2py test environment and with 2.9.12 (pre pyDAL)

With currrent web2py 2.14.5 In both production and SDK GAE various pages fail. 

This failure relates to using a set in a validator:

...
	banks = db(db.CoA.Type == 'Bank')

	form=SQLFORM.factory(
		Field('bank', 'reference CoA', requires=IS_EMPTY_OR(IS_IN_DB(banks, 'CoA.id','%(Name)s'))),
...

Here is the logged error:

[error.txt](https://github.com/web2py/web2py/files/232501/error.txt)


Note IS_IN_DB works fine with IS_IN_SET(db, ...) - I use it all over the place.

In validators.py line 584 is in an if...else construct that tries to check for 'gae'. This test is wrong, the adapter name would be 'google:datastore' which would run the else clause. I tried this and established that the else clause also fails. It looks to me as if this historical work around in validators.py is broken, quite apart from how to fix the test. Perhaps the implementation of 'set' can be changed to be agnostic?

The workaround for me too was to use IS_IN_SET instead:
...
    banks = []
    coa = db(db.CoA.id > 0).select(orderby=db.CoA.Name)
    for c in coa:
        if c.Type == 'Bank':
            banks.append((c.id, c.Name))
...
    form=SQLFORM.factory(
        Field('bank', 'reference CoA', requires=IS_EMPTY_OR(IS_IN_SET(banks))),
...

**Comment by niphlod** [comment]
tracked from hereon at https://github.com/web2py/pydal/issues/352
