### ISSUE TITLE
Error Ticket issued using inbuilt wiki

### ISSUE THREAD

**Issue by benlawraus** [web2py/web2py#933]
Here are the steps
1. Create new application
2. in default.py :
def index():
    return auth.wiki()
3. go to /my-app/default
    page says “Create page “index”
4. go to db.py and insert at the end of file:
auth.wiki(manage_permissions=True,resolve=False)
5. While still logged as Admin, sign up a user X
6. create a page “Q” as X and put “user_1” in the windows “can edit” and “can read”. Add a tag to page “Q”
7. logout user X
8. in db.py change to
auth.settings.registration_requires_approval = True
9. logout as Admin
10. sign up a new user Y
11. login as Admin and go to db admin page and delete “pending” from user Y profile
12. logout Admin
13. login as user Y
14. go to search page from dropdown menu and click on the tag of page “Q”
15 Error Ticket is generated. Login as Admin to see error ticket:
<type 'exceptions.AttributeError'> 'Row' object has no attribute 'can_edit'

Version
web2py™	Version 2.10.3-stable+timestamp.2015.04.02.21.42.07
Python	Python 2.7.6: /usr/bin/python (prefix: /usr)
Traceback
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/www-data/web2py/applications/ae/controllers/default.py", line 59, in <module>
  File "/home/www-data/web2py/gluon/globals.py", line 393, in <lambda>
    self._caller = lambda f: f()
  File "/home/www-data/web2py/applications/ae/controllers/default.py", line 17, in index
    return auth.wiki()
  File "/home/www-data/web2py/gluon/tools.py", line 3872, in wiki
    wiki = self._wiki()
  File "/home/www-data/web2py/gluon/tools.py", line 5715, in __call__
    return self.search()
  File "/home/www-data/web2py/gluon/tools.py", line 6081, in search
    for p in pages]
  File "/home/www-data/web2py/gluon/tools.py", line 5731, in first_paragraph
    if not self.can_read(page):
  File "/home/www-data/web2py/gluon/tools.py", line 5649, in can_read
    set(groups).intersection(set(page.can_read + page.can_edit)) or
  File "/home/www-data/web2py/gluon/packages/dal/pydal/objects.py", line 84, in __getitem__
    raise ae
AttributeError: 'Row' object has no attribute 'can_edit'

**Comment by niphlod** [comment]
closing since https://github.com/web2py/web2py/commit/d7caaf04ccfb3be68e038cbf0930527513dcdaee fixed it
